# -*- coding: utf-8 -*-
"""Génère lot2_ic_mtev.json — QRM originaux EDN (faits collège uniquement)."""
import json
from collections import Counter
from pathlib import Path

OUT = Path(__file__).with_name("lot2_ic_mtev.json")


def Q(item, rang, prompt, opts, correct, explanation, pcz=None, scz=None):
    options = [{"letter": "ABCDE"[i], "text": t, "why": w} for i, (t, w) in enumerate(opts)]
    assert 2 <= len(correct) <= 4, (item, prompt[:50], correct)
    return {
        "item": item, "kind": "QRM", "rang": rang, "prompt": prompt,
        "options": options, "correct": correct, "pcz": pcz or [], "scz": scz or [],
        "explanation": explanation,
    }


questions = []

# =============================================================================
# 234 IC (22) — évite lot1 : OAP+choc déf, FEVG déf, BNP aigu, 4 classes, ttt OAP
# hôpital, clinique/radio/GDS OAP, FDR déclenchants, NYHA, physio, CI ttt
# =============================================================================
questions += [
    Q("234", "A",
      "Un homme de 74 ans, IC connue, décrit une pesanteur de l’hypocondre droit à la marche. Examen : turgescence jugulaire en demi-assis, reflux hépatojugulaire, hépatomégalie ferme douloureuse, œdèmes malléolaires mous blancs prenant le godet. Indiquer la ou les proposition(s) exacte(s).",
      [("Ces signes traduisent la stase veineuse systémique liée à l’élévation de pression dans les cavités droites.", "Physiopathologie des signes droits."),
       ("La turgescence jugulaire est un signe très spécifique, parfois difficile chez l’obèse.", "Le collège le souligne."),
       ("Une ascite précoce est le signe le plus fréquent d’IC droite, avant tout œdème déclive.", "L’ascite est souvent tardive, sauf IT organique ou constriction."),
       ("L’IC gauche est la cause la plus fréquente d’IC droite (IC globale).", "Transmission post-capillaire."),
       ("Hors poussée, la présence de signes physiques d’IC est un élément de gravité.", "Examen souvent pauvre sous traitement.")],
      ["A", "B", "D", "E"],
      "Signes droits = stase veineuse systémique. L’IC gauche en est la 1re cause. L’ascite est tardive. Des signes congestifs persistants marquent la gravité."),
    Q("234", "A",
      "Une femme de 79 ans, HTA, obèse, a une dyspnée d’effort et des OMI. ETT : FEVG 56 %, masse VG indexée 118 g/m², volume AG indexé 42 mL/m² ; NT-proBNP élevé. Indiquer la ou les proposition(s) exacte(s).",
      [("Le tableau est compatible avec une HFpEF, qui représente au moins 50 % des IC, surtout chez la femme âgée hypertendue ou obèse.", "Prédominance HFpEF."),
       ("Le diagnostic associe clinique, FEVG > 50 % (sans valvulopathie significative, anomalie rythmique/conductrice ni péricarde), peptides élevés, et HVG, dilatation AG ou pressions de remplissage.", "Critères du collège."),
       ("HVG : masse VG > 115 g/m² (homme) ou > 95 g/m² (femme) ; dilatation AG : volume indexé > 34 mL/m².", "Seuils écho."),
       ("L’absence de cardiomégalie radiologique élimine une IC.", "Le VG n’est souvent pas dilaté en HFpEF."),
       ("Les gliflozines sont recommandées I-A pour réduire mortalité CV et hospitalisations en HFpEF.", "Seul pilier de haut niveau de preuve.")],
      ["A", "B", "C", "E"],
      "HFpEF : FEVG > 50 % + clinique + BNP + HVG/AG/pressions. Radio normale n’élimine pas. Gliflozines I-A."),
    Q("234", "A",
      "Concernant l’introduction d’un IEC dans l’HFrEF, indiquer la ou les proposition(s) exacte(s).",
      [("On commence à faibles doses, puis on vise si possible les doses d’essais (énalapril 20 mg, captopril 150 mg, ramipril 10 mg) si tolérées.", "Titration."),
       ("PA, créatininémie et kaliémie sont contrôlées à 1 semaine puis à chaque palier.", "Encadré 18.3."),
       ("On baisse ou on arrête si hypotension symptomatique ou créatinine +20–30 %.", "Seuil de tolérance."),
       ("IEC et antialdostérone doivent être introduits le même jour.", "Introduction simultanée à éviter (hyperK, IR)."),
       ("Prudence si sujet âgé, déshydraté, sous fortes doses de diurétiques, diabétique, IR, ou PAS < 100 mmHg.", "Populations à risque.")],
      ["A", "B", "C", "E"],
      "IEC : faibles doses, surveillance J7, créatinine +20–30 % = baisser. Pas d’introduction simultanée avec un antialdostérone."),
    Q("234", "A",
      "Concernant les bêtabloquants de l’HFrEF, indiquer la ou les proposition(s) exacte(s).",
      [("Seuls carvédilol, métoprolol, bisoprolol et nébivolol ont une efficacité démontrée.", "Quatre molécules."),
       ("Introduction chez un patient stabilisé, à très faibles doses (carvédilol 3,125 mg × 2/j ou bisoprolol 1,25 mg/j), paliers hebdomadaires.", "Encadré 18.4."),
       ("Les introduire d’emblée pendant une poussée aiguë serait une faute.", "Texte explicite."),
       ("Chez un patient déjà sous BB, l’arrêt est recommandé d’emblée à chaque hospitalisation pour IC.", "On n’arrête que si mauvaise réponse ou choc."),
       ("CI : asthme ou BPCO sévère, bradycardie ou hypotension symptomatique, BAV 2 ou 3.", "Encadré 18.4.")],
      ["A", "B", "C", "E"],
      "Quatre BB, titration lente, jamais pendant la poussée. On ne les coupe pas d’emblée en décompensation, sauf choc."),
    Q("234", "A",
      "Homme de 62 ans, IDM antérieur il y a 3 mois, NYHA II, FEVG 28 % sous ttt optimal, pas de TV, survie estimée > 1 an. Indiquer la ou les proposition(s) exacte(s) sur le DAI.",
      [("Prévention primaire possible : FEVG < 35 %, NYHA II–III, cardiopathie ischémique ≥ 6 semaines après IDM ou revascularisation.", "Critères primaires."),
       ("Prévention secondaire : FV récupérée ou TV symptomatique.", "Définition."),
       ("Le NYHA IV relève d’un DAI de principe car le risque de mort subite y est maximal.", "NYHA IV : DAI non indiqué (survie < 1 an) sauf greffe/assistance."),
       ("En non ischémique, on attend ≥ 3 mois de traitement médical bien conduit.", "Délai."),
       ("Complications : infections de sonde et chocs inappropriés.", "Cités.")],
      ["A", "B", "D", "E"],
      "DAI primaire si NYHA II–III, FEVG < 35 %, délais respectés, survie > 1 an. Pas au stade IV de principe."),
    Q("234", "B",
      "Femme de 58 ans, CMD non ischémique, NYHA III, FEVG 32 %, QRS 160 ms en BBG. Indiquer la ou les proposition(s) exacte(s) sur la resynchronisation.",
      [("Indication : IC symptomatique NYHA II–IV, FEVG ≤ 35 %, QRS ≥ 130 ms.", "Critères."),
       ("Sondes : atrium droit, VD, et paroi latérale du VG via le sinus coronaire.", "Technique."),
       ("Meilleure réponse si BBG, QRS ≥ 150 ms et cardiopathie non ischémique.", "Facteurs de réponse."),
       ("Un QRS fin (< 120 ms) est le meilleur prédicteur de réponse.", "C’est l’élargissement qui fonde l’indication."),
       ("Un dispositif combinant DAI et resynchronisation est possible si les deux indications coexistent.", "CRT-D.")],
      ["A", "B", "C", "E"],
      "CRT si NYHA II–IV, FEVG ≤ 35 %, QRS ≥ 130 ms. Meilleure si BBG large non ischémique. CRT-D si DAI aussi indiqué."),
    Q("234", "B",
      "Concernant le traitement de l’HFpEF (FEVG > 50 %), indiquer la ou les proposition(s) exacte(s).",
      [("Les gliflozines ont une recommandation I-A sur mortalité CV et hospitalisations.", "Haut niveau de preuve."),
       ("Le moyen mnémotechnique ABCDEFG inclut le ralentissement de la FC (BB ou ICa ralentisseur) pour allonger la diastole.", "Item A."),
       ("Diurétiques (thiazidique ou anse) si congestion, avec surveillance rénale.", "Item D."),
       ("Le tafamidis est un traitement spécifique de l’amylose ATTR.", "Rang A du paragraphe."),
       ("Toute activité physique est contre-indiquée en HFpEF.", "Au contraire, exercices adaptés recommandés.")],
      ["A", "B", "C", "D"],
      "HFpEF : gliflozines I-A, FC/PA, diurétiques si congestion, comorbidités, exercice, tafamidis si amylose ATTR."),
    Q("234", "A",
      "Devant un OAP ou un choc, le collège fait rechercher des causes spécifiques (CHAMPIT). Indiquer la ou les proposition(s) exacte(s).",
      [("C : SCA ; H : urgence hypertensive.", "Deux premières lettres."),
       ("A : arythmie ; M : cause mécanique d’un SCA (rupture, CIV, IM aiguë).", "Lettres A et M."),
       ("P : embolie pulmonaire ; I : infections ; T : tamponnade.", "Lettres P, I, T."),
       ("T signifie thrombose veineuse superficielle, qui impose une fibrinolyse systématique.", "T = tamponnade."),
       ("Ce dépistage s’ajoute au traitement symptomatique urgent, il ne le remplace pas.", "Diurétique, nitrés ou inotropes selon le tableau.")],
      ["A", "B", "C", "E"],
      "CHAMPIT = SCA, HTA maligne, arythmie, mécanique de SCA, EP, infection, tamponnade. En parallèle du ttt d’urgence."),
    Q("234", "A",
      "Homme de 70 ans, marbré, oligurique, obnubilé, PAS 78 mmHg, extrémités froides ; ETT : bas débit VG. Indiquer la ou les proposition(s) exacte(s).",
      [("Inotrope : dobutamine IV, ou inhibiteur des phosphodiestérases (milrinone, énoximone) si le patient est sous BB.", "Algorithme du choc."),
       ("Sonde urinaire et monitorage invasif de la PA (cathéter radial).", "Surveillance."),
       ("Nitrés IV à forte dose tant que la PAS n’est pas corrigée.", "Nitrés si PAS > 110 mmHg dans l’OAP, pas dans le choc."),
       ("Si échec : ECMO, assistance, cœur artificiel ou greffe en urgence.", "Escalade."),
       ("Le lévosimendan (inotrope et vasodilatateur) est parfois utilisé si sevrage difficile des inotropes.", "Mentionné.")],
      ["A", "B", "D", "E"],
      "Choc : dobutamine (milrinone si BB), sonde urinaire, PA invasive. Pas de nitrés. Escalade assistance/greffe."),
    Q("234", "A",
      "Au domicile, femme de 81 ans en OAP, consciente, PAS 145/80 mmHg. Indiquer la ou les mesure(s) immédiate(s) exacte(s) selon le collège.",
      [("Position assise ou demi-assise.", "Premier geste."),
       ("Furosémide IV 1 mg/kg, à répéter si besoin.", "Dose domicile."),
       ("Nitrés sublinguaux si PAS > 100 mmHg.", "Seuil domicile (à l’hôpital : nitrés IV si PAS > 110)."),
       ("Appel du Samu selon gravité et hospitalisation.", "Urgence."),
       ("IEC à dose maximale avant l’arrivée du Samu.", "IEC/ARNI seulement après la poussée.")],
      ["A", "B", "C", "D"],
      "Domicile : assis, furosémide 1 mg/kg IV, nitrés SL si PAS > 100, Samu. Pas d’IEC pendant la poussée."),
    Q("234", "A",
      "Concernant la radiographie thoracique dans l’IC, indiquer la ou les proposition(s) exacte(s).",
      [("Cardiomégalie si RCT > 0,5 ; son absence n’élimine pas une IC, surtout à FE préservée.", "Piège HFpEF."),
       ("Stase par gravité croissante : redistribution vers les sommets, puis Kerley/flou hilaire, puis œdème alvéolaire.", "Séquence."),
       ("Œdème alvéolaire : opacités floconneuses, souvent « ailes de papillon », parfois unilatérales trompeuses.", "Sémiologie."),
       ("Épanchements pleuraux uni- ou bilatéraux possibles.", "Associés."),
       ("La radio n’a plus aucune place en dyspnée aiguë depuis l’ETT.", "Elle reste primordiale pour le retentissement pleuropulmonaire.")],
      ["A", "B", "C", "D"],
      "Radio : RCT, redistribution, Kerley, ailes de papillon, pleurésie. Pas de cardiomégalie n’élimine pas l’HFpEF."),
    Q("234", "A",
      "Homme de 48 ans, HFrEF de novo, FEVG 25 %, VG dilaté, coronaire inconnue. Indiquer la ou les proposition(s) exacte(s).",
      [("Les cardiopathies ischémiques sont la 1re cause d’IC : il faut l’éliminer (coro, ou coroscanner si jeune/probabilité faible).", "Notion indispensable."),
       ("Coronaire normale : CMD (maladie du muscle), familiale dans ~25 % des cas.", "Après exclusion ischémique/valvulaire/HTA."),
       ("Causes de CMD : alcool, cocaïne, myocardite, auto-immun, endocrine, carence, chimiothérapie, péripartum, takotsubo.", "Liste."),
       ("Une valvulopathie gauche ne se complique jamais d’IC tant que la FEVG reste > 40 %.", "Toute valvulopathie peut décompenser ; le RM peut donner un OAP à VG sain."),
       ("L’HTA agit par HVG/fibrose (souvent HFpEF), par maladie coronaire, et/ou par postcharge chronique.", "Mécanismes.")],
      ["A", "B", "C", "E"],
      "Toujours chercher une ischémie devant une HFrEF. Sinon CMD (25 % familiales). HTA : HFpEF et/ou HFrEF. Les valves, y compris le RM, peuvent décompenser."),
    Q("234", "A",
      "Concernant l’IC droite isolée, indiquer la ou les étiologie(s) retenue(s) par le collège.",
      [("Cœur pulmonaire des pneumopathies hypoxémiantes et cœur pulmonaire aigu de l’EP massive.", "Poumon/EP."),
       ("HTAP primitive ou secondaire à une connectivite (sclérodermie).", "HTAP."),
       ("DAVD, infarctus du VD, péricardite constrictive.", "Causes cardiaques/péricardiques."),
       ("IT isolée : traumatique, endocardite du toxicomane, carcinoïde.", "Tricuspide."),
       ("Elle est presque toujours due à un RM serré avec VG dilaté.", "Le RM donne un OAP ; l’IC gauche reste la 1re cause d’ICD (forme globale).")],
      ["A", "B", "C", "D"],
      "ICD isolée : poumon, EP, HTAP, DAVD, infarctus VD, constriction, IT organique. L’IC gauche reste toutefois la 1re cause d’ICD."),
    Q("234", "A",
      "Concernant l’ETT dans l’IC, indiquer la ou les proposition(s) exacte(s).",
      [("Examen clé : type d’IC selon la FEVG, étiologie curable, hémodynamique, traitement.", "Rôle central."),
       ("Elle évalue VG/VD/atria, FEVG (normale > 50–60 %), VCI, valves, pressions de remplissage, débit et PAP.", "Paramètres."),
       ("Cinétique segmentaire → ischémie ; HVG asymétrique septale → CMH.", "Orients."),
       ("L’ETT n’est indiquée qu’après échec du BNP, jamais si les peptides sont élevés.", "Au contraire : ETT si BNP > 35 ou NT-proBNP > 125 en chronique, ou forte suspicion."),
       ("Hors urgence, seuils d’exclusion : BNP < 35 pg/mL ou NT-proBNP < 125 pg/mL.", "Seuils chroniques (différents des seuils d’urgence déjà traités).")],
      ["A", "B", "C", "E"],
      "ETT indispensable. En chronique, BNP < 35 ou NT-proBNP < 125 rendent l’IC improbable ; au-delà, ETT."),
    Q("234", "A",
      "Quelles mesures hygiénodiététiques de l’IC chronique sont exactes ?",
      [("Cible de 5 à 6 g de sel par jour.", "Régime."),
       ("Pesée : consulter si +2 à 3 kg, a fortiori en 2–3 jours ; une perte progressive sans œdème oriente vers une dénutrition de mauvais pronostic.", "Alerte pondérale."),
       ("Marche régulière non essoufflante hors décompensation ; le repos strict n’est plus souhaitable.", "Déconditionnement."),
       ("Seule la vaccination antigrippale est retenue ; pneumocoque et Covid-19 n’ont pas leur place.", "Les trois vaccins (grippe, Covid-19, pneumocoque) sont recommandés."),
       ("En CMD alcoolique, une consommation modérée d’alcool est recommandée pour le HDL.", "Arrêt total, parfois régression de la CMD.")],
      ["A", "B", "C"],
      "Sel 5–6 g/j, poids (+2–3 kg/2–3 j), activité hors poussée, vaccins, arrêt alcool/tabac."),
    Q("234", "A",
      "Concernant les traitements de 2e intention de l’HFrEF encore symptomatique, indiquer la ou les proposition(s) exacte(s).",
      [("Ivabradine (bloc If) si NYHA II–IV, rythme sinusal, FC > 70 ou 75/min malgré BB (ou CI) : réduit les hospitalisations.", "Indication."),
       ("Digoxine : symptômes ± FA pour ralentir la FC ; effet neutre sur la survie ; marge étroite, dosage plasmatique.", "Profil."),
       ("Amiodarone : seul antiarythmique de l’HFrEF (TV graves, prévention des récidives de FA) ; pas de baisse de mortalité prouvée.", "Seul AA autorisé."),
       ("Le flécaïnide est l’antiarythmique de 1re intention en HFrEF pour la FA.", "Classe I contre-indiquée."),
       ("Nitrés oraux : appoint si pressions de remplissage encore élevées.", "Vasodilatateurs veineux.")],
      ["A", "B", "C", "E"],
      "2e ligne : ivabradine (sinusal, FC élevée), digoxine, nitrés d’appoint, amiodarone. Pas de flécaïnide."),
    Q("234", "A",
      "Concernant l’évolution chiffrée de l’IC, indiquer la ou les proposition(s) exacte(s).",
      [("Mortalité ~50 % à 5 ans ; jusqu’à 40–50 % par an en NYHA IV.", "Chiffres."),
       ("Décès : mort subite (TV/FV) ou IC réfractaire.", "Mécanismes."),
       ("Une hospitalisation pour décompensation est toujours un facteur de gravité ; l’IC est une des 1res causes d’hospitalisation après 65 ans.", "Réhospitalisations."),
       ("Prévalence 1–2 % ; âge moyen du diagnostic en Europe 75–80 ans (~78 ans dans les Points).", "Épidémiologie."),
       ("QRS fin et natrémie normale sont les deux facteurs les plus péjoratifs.", "Péjoratifs : NYHA III–IV, FEVG basse, QRS > 120 ms, hyponatrémie, BNP, pic VO2 bas.")],
      ["A", "B", "C", "D"],
      "Prévalence 1–2 %, diagnostic vers 75–80 ans, mortalité ~50 % à 5 ans. Gravité : réhospitalisations, NYHA III–IV, QRS large, hyponatrémie."),
    Q("234", "A",
      "Femme de 66 ans, OAP, PAS 198/102 mmHg, sans choc. Indiquer la ou les proposition(s) exacte(s).",
      [("Une poussée hypertensive peut accompagner un OAP ; une PAS élevée n’élimine pas le diagnostic.", "OAP hypertensif."),
       ("Nitrés IV indiqués car PAS > 110 mmHg.", "Seuil hospitalier."),
       ("Nicardipine IV 1 à 5 mg/h possible pour la poussée hypertensive.", "Posologie du ttt d’OAP."),
       ("La dobutamine est le traitement de 1re intention de cet OAP sans hypoperfusion.", "Inotropes = choc."),
       ("HBPM préventive systématique à l’hôpital.", "Mesure associée.")],
      ["A", "B", "C", "E"],
      "OAP hypertensif : nitrés si PAS > 110, nicardipine 1–5 mg/h, diurétique, HBPM. Pas de dobutamine sans choc."),
    Q("234", "A",
      "Selon l’ESC 2021, quels examens biologiques simples sont demandés devant une IC, en plus d’ECG, ETT et radio ?",
      [("Natrémie, kaliémie, créatininémie.", "Rein et iono."),
       ("BNP ou NT-proBNP, glycémie à jeun et HbA1c, bilan lipidique et hépatique, TSHus.", "Terrain métabolique."),
       ("NFS, ferritine et CST ne font pas partie du bilan ESC, réservés à l’hématologue.", "NFS et bilan martial sont demandés (anémie, carence fréquentes)."),
       ("Hémocultures et coproculture systématiques même sans fièvre.", "Non prévu."),
       ("Ces comorbidités (fer, IR, thyroïde) décompensent et limitent la tolérance des cardioprotecteurs.", "Paragraphe comorbidités.")],
      ["A", "B", "E"],
      "Bilan ESC : Na, K, créatinine, peptides, glucose/HbA1c, lipides, foie, TSH, NFS, fer. Traiter les comorbidités."),
    Q("234", "A",
      "Quelles situations correspondent à une IC à débit augmenté ?",
      [("Anémies chroniques.", "Haut débit."),
       ("Fistules artérioveineuses (dialyse, Rendu-Osler).", "Citées."),
       ("Hyperthyroïdie, carence en thiamine (béribéri), maladie de Paget (rare).", "Liste."),
       ("Rétrécissement aortique serré par obstacle à l’éjection.", "Surcharge de pression, pas haut débit."),
       ("Une augmentation permanente du débit peut surcharger le cœur en volume.", "Mécanisme.")],
      ["A", "B", "C", "E"],
      "Haut débit : anémie chronique, FAV, hyperthyroïdie, béribéri, Paget. Le RA est l’inverse."),
    Q("234", "A",
      "Concernant le sacubitril/valsartan dans l’HFrEF, indiquer la ou les proposition(s) exacte(s).",
      [("Inhibition AT1 + néprilysine → potentialisation des peptides natriurétiques.", "Mécanisme."),
       ("Supériorité vs énalapril sur mortalité et hospitalisations pour IC aiguë.", "Étude princeps."),
       ("1re intention IIb-B, ou relais d’IEC si symptômes persistants sous ttt optimal (I-B).", "Double positionnement."),
       ("Introduction en pleine poussée d’OAP, avant tout diurétique.", "ARNI seulement après la poussée."),
       ("Les ARA2 isolés sont surtout réservés aux intolérants aux IEC (moins de toux).", "Place des ARA2.")],
      ["A", "B", "C", "E"],
      "ARNI > IEC sur mortalité/hospitalisations ; 1re intention IIb ou relais si symptômes. Pas pendant l’OAP."),
    Q("234", "A",
      "Homme de 71 ans, IC ischémique, deux hospitalisations en 6 mois, NYHA III, PAS 95 mmHg, QRS 140 ms, Na 128 mmol/L, NT-proBNP très élevé, pic VO2 bas. Indiquer la ou les proposition(s) exacte(s).",
      [("NYHA III–IV, réhospitalisations, étiologie ischémique et hypotension sont péjoratifs.", "Facteurs cliniques."),
       ("QRS > 120 ms (BBG) est un facteur ECG péjoratif, avec une implication de resynchronisation possible.", "Pont CRT."),
       ("Hyponatrémie et BNP/NT-proBNP élevés sont des biomarqueurs de mauvais pronostic.", "Biologie."),
       ("Un pic VO2 très abaissé a une valeur pronostique et peut faire discuter une greffe si le patient est éligible.", "VO2."),
       ("Un pic VO2 bas impose d’arrêter les quatre classes cardioprotectrices et contre-indique toute greffe.", "C’est l’inverse : le pic bas oriente vers la greffe ; CI si RAP > 5 UW.")],
      ["A", "B", "C", "D"],
      "Péjoratifs : NYHA III–IV, réhospitalisations, ischémie, hypotension, QRS large, hyponatrémie, BNP, pic VO2 bas (discussion de greffe)."),
]

# =============================================================================
# 203 Dyspnée (12) — évite lot1 : définition, gravité, étiologies fréquentes adulte,
# bilan 1re intention/biomarqueurs, analyse sémiologique, orientation cardiaque/EP
# =============================================================================
questions += [
    Q("203", "A",
      "Femme de 69 ans, HTA, 15 PA, IMC 32, essoufflement depuis six semaines. Indiquer la ou les proposition(s) exacte(s) sur le bilan d’une dyspnée chronique.",
      [("Le bilan peut se faire sans urgence, contrairement à la dyspnée aiguë.", "Distinction."),
       ("NFS d’abord : toujours éliminer une anémie avant des investigations plus poussées.", "Consigne."),
       ("On discute EFR-GDS, ECG, ETT-Doppler, radio, épreuve d’effort avec gaz et VO2.", "Liste."),
       ("L’épreuve d’effort n’a aucun intérêt : seule l’EVA cote objectivement la gêne.", "L’épreuve d’effort métabolique objective la gêne et oriente cœur vs poumon."),
       ("Un angioscanner est systématique en 1re intention, avant la NFS.", "Pas le bilan chronique d’emblée.")],
      ["A", "B", "C"],
      "Chronique : pas d’urgence, NFS d’abord, puis EFR, ECG, ETT, radio, épreuve d’effort. Angioscanner non systématique."),
    Q("203", "A",
      "Concernant l’HTAP définie dans ce chapitre, indiquer la ou les proposition(s) exacte(s).",
      [("HTAP précapillaire : PAPm > 25 mmHg au repos (ou > 30 à l’effort) et pression capillaire < 15 mmHg au cathétérisme droit.", "Définition."),
       ("Le terme HTAP est réservé à l’élévation isolée des pressions artérielles pulmonaires ; sinon on parle d’HTP (gauche, respiratoire, post-embolique).", "Terminologie."),
       ("Étiologies : idiopathique, familiale, sclérodermie, shunt, VIH, anorexigènes (dexfenfluramine).", "Liste."),
       ("Dyspnée à tout âge, examen et radio souvent pauvres ; évoquée à l’ETT, confirmée par le cathétérisme.", "Parcours."),
       ("La radio de thorax suffit à affirmer l’HTAP sans cathétérisme.", "Confirmation hémodynamique.")],
      ["A", "B", "C", "D"],
      "HTAP : PAPm > 25 (ou > 30 à l’effort) et PCAP < 15 mmHg. ETT puis cathétérisme droit."),
    Q("203", "A",
      "Chez l’enfant, concernant la dyspnée aiguë, indiquer la ou les proposition(s) exacte(s).",
      [("Étiologies les plus fréquentes : corps étranger, laryngite, épiglottite.", "Points."),
       ("Causes laryngées : dyspnée inspiratoire, cornage, tirage, souvent dysphonie.", "Sémiologie."),
       ("La gravité du Quincke et des causes neuromusculaires (polyradiculonévrite) est souvent sous-estimée.", "Mise en garde."),
       ("Le corps étranger inhalé concerne surtout l’adulte âgé, rarement l’enfant.", "Surtout l’enfant."),
       ("Un œdème de Quincke avec œdème de glotte s’intègre souvent à un choc anaphylactique.", "Contexte.")],
      ["A", "B", "C", "E"],
      "Enfant : corps étranger, laryngite, épiglottite. Inspiratoire + cornage. Ne pas sous-estimer Quincke et Guillain-Barré."),
    Q("203", "A",
      "Concernant le SDRA, indiquer la ou les proposition(s) exacte(s).",
      [("Défaillance pulmonaire aiguë sévère, perméabilité alvéolocapillaire accrue, mortalité élevée.", "Définition."),
       ("Œdème lésionnel, principal DD : OAP hémodynamique.", "Lien item 234."),
       ("Causes : pneumopathie, sepsis, inhalation, EP, traumatisme, choc, toxiques.", "Liste."),
       ("Hospitalisation en réanimation.", "Urgence."),
       ("Un furosémide 1 mg/kg IV suffit en règle, comme dans l’OAP cardiogénique.", "PEC de réanimation, pas un simple diurétique.")],
      ["A", "B", "C", "D"],
      "SDRA = œdème lésionnel de réanimation. Ne pas le traiter comme un OAP."),
    Q("203", "A",
      "Homme longiligne de 22 ans, fumeur : douleur latérothoracique brutale à l’effort, tympanisme, abolition des VV et du MV. Indiquer la ou les proposition(s) exacte(s).",
      [("Le tableau oriente vers un pneumothorax.", "Terrain + physique."),
       ("La radio recherche une hyperclarté.", "Signe."),
       ("L’épanchement pleural est une autre cause pleurale de dyspnée aiguë.", "Même paragraphe."),
       ("Crépitants en marée montante et expectoration saumonée sont attendus.", "Signes d’OAP, pas de PNO."),
       ("Un traumatisme peut associer PNO, hémothorax, volet, contusion, hémopéricarde.", "Traumatismes.")],
      ["A", "B", "C", "E"],
      "PNO : longiligne/tabac, silence + tympanisme, hyperclarté. Pas de crépitants d’OAP."),
    Q("203", "A",
      "Concernant causes extrathoraciques et pièges, indiquer la ou les proposition(s) exacte(s).",
      [("Acidose et anémie entraînent davantage une polypnée qu’une dyspnée.", "Points."),
       ("Toujours penser à l’anémie, y compris en chronique.", "Indispensable."),
       ("CO, méthémoglobinémie et sulfhémoglobinémie sont des causes de trouble du transport de l’O2.", "Autres causes."),
       ("L’OAP est souvent porté par excès chez le BPCO encombré.", "Piège."),
       ("La NFS est inutile si l’auscultation pulmonaire est anormale.", "La NFS reste un examen de 1re intention.")],
      ["A", "B", "C", "D"],
      "Anémie/acidose : polypnée. Piège OAP chez le BPCO. NFS toujours."),
    Q("203", "A",
      "Un BPCO de 72 ans, ronchi et expectoration, est étiqueté OAP d’emblée. Quelles mises en garde du collège s’appliquent ?",
      [("Chez le BPCO, l’encombrement fait souvent porter à tort un OAP.", "Point."),
       ("L’EP sur terrain emphysémateux est un tableau trompeur.", "Piège."),
       ("Le pseudoasthme cardiaque (subœdème bronchospastique) peut mimer une crise d’asthme.", "Piège inverse."),
       ("Des sibilants éliminent toute cause cardiaque.", "Le pseudoasthme cardiaque a des sibilants ± crépitants."),
       ("Exacerbation de BPCO : majoration de dyspnée, toux, volume ou purulence des expectorations, souvent surinfectée.", "Définition.")],
      ["A", "B", "C", "E"],
      "Ne pas étiqueter OAP tout BPCO encombré. Penser EP. Les sibilants n’excluent pas le cœur."),
    Q("203", "A",
      "Concernant les échelles d’intensité autres que la NYHA, indiquer la ou les proposition(s) exacte(s).",
      [("MRC 0 (exercice intense) à 4 (empêche de sortir ou survient à l’habillement).", "Échelle pneumo."),
       ("MRC 3 : arrêt après ~100 m ou quelques minutes.", "Stade 3."),
       ("EVA 10 cm possible pour une dyspnée aiguë.", "Outil."),
       ("Borg 0–10, y compris après un exercice prédéterminé.", "Outil."),
       ("Le nombre d’oreillers n’a aucun lien avec l’orthopnée.", "Le collège le recueille précisément pour coter l’orthopnée.")],
      ["A", "B", "C", "D"],
      "MRC 0–4, EVA, Borg, nombre d’oreillers. Complémentaires de la NYHA."),
    Q("203", "A",
      "Femme de 35 ans : dyspnée inspiratoire brutale, cornage, tirage, urticaire et collapsus après un repas. Indiquer la ou les proposition(s) exacte(s).",
      [("Évoquer un œdème de Quincke avec œdème de glotte, souvent anaphylactique.", "Cause laryngée."),
       ("La gravité des causes laryngées est fréquemment sous-estimée.", "Points."),
       ("Dysphonie fréquente si origine laryngée.", "Signe."),
       ("Le tableau typique est une dyspnée expiratoire à sibilants, identique à l’asthme.", "Laryngé = inspiratoire + cornage."),
       ("Sténose tumorale, granulome post-intubation et corps étranger figurent parmi les causes trachéales.", "Liste.")],
      ["A", "B", "C", "E"],
      "Quincke : inspiratoire, cornage, anaphylaxie. Urgence sous-estimée. Différent de l’asthme."),
    Q("203", "A",
      "Concernant platypnée-orthodéoxie et HTP post-embolique, indiquer la ou les proposition(s) exacte(s).",
      [("Dyspnée en orthostatisme avec désaturation : rechercher un shunt D-G (FOP).", "Définition."),
       ("L’HTP post-embolique est une complication grave précapillaire persistante après une ou plusieurs EP.", "Rang A."),
       ("La platypnée est synonyme d’orthopnée.", "Platypnée = debout ; orthopnée = décubitus."),
       ("Les dyspnées chroniques sont le plus souvent cardiaques ou pulmonaires.", "Synthèse."),
       ("Constriction péricardique et toutes causes d’IC figurent parmi les causes cardiaques chroniques.", "Liste.")],
      ["A", "B", "D", "E"],
      "Platypnée-orthodéoxie = FOP. HTP-TEC = complication de la MTEV. Chronique : cœur ou poumon."),
    Q("203", "A",
      "Asthmatique qui ne peut plus parler, thorax bloqué en inflation, plus de sibilants ni de MV. Indiquer la ou les proposition(s) exacte(s).",
      [("Il faut distinguer crise d’asthme et asthme aigu grave, urgence vitale.", "Distinction."),
       ("Asthme aigu grave : thorax bloqué, silence auscultatoire, pouls paradoxal possible, élocution impossible.", "Signes."),
       ("La crise non grave est une dyspnée expiratoire à sibilants.", "Tableau simple."),
       ("La disparition des sibilants signe toujours la guérison, autorisant le retour à domicile.", "C’est un signe d’extrême gravité."),
       ("Gravité d’une BPCO décompensée : dyspnée de repos, cyanose, désaturation, FR > 25/min, choc ou signes neuro, hypercapnie.", "Critères BPCO.")],
      ["A", "B", "C", "E"],
      "Silence auscultatoire = asthme aigu grave, pas une guérison. Transposer les signes de gravité à la BPCO."),
    Q("203", "A",
      "MRC, Cheyne-Stokes et causes neurologiques : indiquer la ou les proposition(s) exacte(s).",
      [("MRC 2 : marche à plat plus lente que les gens du même âge, ou arrêt si le patient marche à son rythme.", "Stade 2."),
       ("Cheyne-Stokes (origine centrale, bas débit des centres) se voit dans l’IC grave.", "Mécanisme."),
       ("Kussmaul (inspiration-pause-expiration-pause) oriente vers une acidose métabolique.", "Cause extrathoracique."),
       ("Causes neuro aiguës : bulbe, polyradiculonévrite, myasthénie.", "Rang A."),
       ("Cheyne-Stokes signe une EP à haut risque et impose une fibrinolyse.", "C’est un signe d’IC grave, pas d’EP.")],
      ["A", "B", "C", "D"],
      "MRC 2 = ralentissement à plat. Cheyne-Stokes : IC grave. Kussmaul : acidose. Neuro : bulbe, Guillain-Barré, myasthénie."),
]

# =============================================================================
# 226 MTEV (20) — évite lot1 : définitions, FDR temporaires, Wells TVP, scores EP,
# D-dimères, stratification, ACO initial, durée, compression/contraception, stratégie diag
# =============================================================================
questions += [
    Q("226", "A",
      "Femme de 64 ans en choc (PAS 75 mmHg depuis 20 min), dyspnée brutale, sans sepsis ni saignement. ETT au lit : VD dilaté, septum paradoxal ; scanner impossible. Indiquer la ou les proposition(s) exacte(s).",
      [("EP à haut risque (choc/hypotension) : mortalité > 15 %, PEC en USIC/réanimation.", "Filière."),
       ("Si l’angioscanner est impossible, la surcharge droite à l’ETT peut suffire à fibrinolyser.", "Algo haut risque."),
       ("Fibrinolyse recommandée en EP grave hors CI ; sinon embolectomie d’urgence.", "Traitement."),
       ("Hors choc, pas de fibrinolyse systématique en EP intermédiaire.", "Texte explicite."),
       ("L’absence de surcharge droite en choc rend l’EP très probable et impose la fibrinolyse de principe.", "L’absence de signes droits rend l’EP peu probable.")],
      ["A", "B", "C", "D"],
      "Haut risque = choc → USIC + fibrinolyse (ou embolectomie). ETT si scanner impossible. Pas de fibrinolyse systématique hors choc."),
    Q("226", "A",
      "Concernant l’échodoppler veineux des MI, indiquer la ou les proposition(s) exacte(s).",
      [("Examen de 1re intention pour une TVP, Se et Sp > 95 %.", "Performance."),
       ("Veine normale : pas de matériel, compressible, Doppler respiratoire augmenté par la chasse.", "Critères de normalité."),
       ("TVP : thrombus direct et/ou incompressibilité ; Doppler diminué/aboli.", "Critères positifs."),
       ("En suspicion d’EP, une TVP distale isolée suffit à confirmer l’EP sans imagerie pulmonaire.", "Seule une TVP proximale confirme une suspicion d’EP."),
       ("Un Doppler veineux normal n’élimine pas une EP.", "Notion clé.")],
      ["A", "B", "C", "E"],
      "EDV = référence de la TVP. Proximale + suspicion d’EP = diagnostic d’EP. Distale ou Doppler normal ≠ exclusion d’EP."),
    Q("226", "A",
      "Devant une jambe douloureuse unilatérale à signes dissociés, quels diagnostics différentiels de TVP le collège cite-t-il ?",
      [("Claquage, kyste synovial, insuffisance veineuse ou SPT.", "Musculo-veineux."),
       ("Érysipèle, lymphangite, cellulite, lymphœdème.", "Infectieux/lymphatique."),
       ("Compression extrinsèque (adénopathies, tumeur, utérus gravide), sciatique.", "Compressif."),
       ("IC droite, insuffisance rénale ou hépatique (œdèmes souvent bilatéraux).", "Général."),
       ("La clinique seule confirme une TVP dès qu’il existe une douleur de mollet.", "Orientation seulement ; preuve objective obligatoire.")],
      ["A", "B", "C", "D"],
      "Clinique insuffisante. Différentiel large : traumatisme, kyste, infection cutanée, lymphœdème, compression, causes générales."),
    Q("226", "A",
      "Concernant l’HNF dans la MTEV (chapitre 226), indiquer la ou les proposition(s) exacte(s).",
      [("500 UI/kg/j, TCA 1,5–2,5 × témoin ou anti-Xa 0,3–0,7 U.", "Schéma 226."),
       ("Indiquée si ClCr < 30 mL/min, instabilité, geste imminent, ou fibrinolyse.", "Indications résiduelles."),
       ("Plaquettes 2×/semaine pendant 21 jours ; NFS avant toute héparine.", "TIH."),
       ("Cette surveillance n’est plus nécessaire au-delà d’un mois.", "Mention."),
       ("En IR sévère, les HBPM restent préférées car elles n’imposent aucune surveillance.", "HBPM/fonda CI si DFG < 30 ; l’HNF est alors indiquée.")],
      ["A", "B", "C", "D"],
      "HNF 226 : 500 UI/kg/j, TCA 1,5–2,5, IR sévère/instabilité/fibrinolyse, plaquettes 21 j."),
    Q("226", "A",
      "Concernant le filtre cave, indiquer la ou les proposition(s) exacte(s).",
      [("Suggéré si CI aux anticoagulants.", "1re indication."),
       ("Aussi si récidive sous traitement bien conduit, ou après embolectomie d’EP massive.", "Autres indications."),
       ("Le filtre temporaire doit être retiré dès que la CI n’existe plus (risque thrombotique).", "Retrait."),
       ("Recommandé d’emblée dans toute TVP distale ambulatoire.", "Pas une indication."),
       ("Ce n’est pas un substitut de l’anticoagulation lorsqu’elle est possible.", "Pas un ttt de routine.")],
      ["A", "B", "C", "E"],
      "Filtre : CI aux ACO, récidive sous ttt, post-embolectomie. À retirer. Pas de principe."),
    Q("226", "B",
      "Homme de 71 ans, EP et cancer colique en chimiothérapie. Indiquer la ou les proposition(s) exacte(s).",
      [("HBPM prolongée : moins de récidives que les AVK dans les études citées.", "Supériorité HBPM."),
       ("Daltéparine 200 UI/kg/j 1 mois puis 150 ; tinzaparine 175 UI/kg/j ; énoxaparine 150 UI/kg/j.", "Doses d’études."),
       ("Plaquettes < 50 G/L : interrompre l’HBPM, reprendre au-dessus de ce seuil.", "Thrombopénie chimio."),
       ("Certains AOD d’emblée possibles, sauf cancers digestifs et génito-urinaires.", "Restriction organe."),
       ("Relais AVK INR 3–4 dès J1 pendant 6 mois, préféré aux HBPM.", "6 premiers mois : HBPM.")],
      ["A", "B", "C", "D"],
      "Cancer : HBPM (doses d’études) tant que le cancer est actif ; stop si plaquettes < 50 G/L. AOD hors cancers digestifs/GU."),
    Q("226", "A",
      "Femme enceinte 28 SA, dyspnée brutale. Indiquer la ou les proposition(s) exacte(s).",
      [("D-dimères souvent faussement positifs.", "Limite."),
       ("EDV en 1re intention.", "Stratégie."),
       ("L’angioscanner est formellement contre-indiqué tout au long de la grossesse, quelle que soit la technique.", "Le cours indique que scanner et scintigraphie peuvent être utilisés avec les techniques actuelles."),
       ("Traitement : HBPM ; AVK non recommandés aux 1er et 3e trimestres.", "PEC."),
       ("Le rivaroxaban d’emblée est le traitement de référence tout au long de la grossesse.", "Le collège retient les HBPM.")],
      ["A", "B", "D"],
      "Grossesse : D-dimères peu spécifiques, EDV d’abord ; scanner/scinti possibles si besoin. HBPM, pas d’AVK aux T1/T3."),
    Q("226", "A",
      "TVP distale jambière symptomatique isolée confirmée. Indiquer la ou les proposition(s) exacte(s).",
      [("Une TVP distale diagnostiquée se prend en charge comme une proximale (ACO).", "Rang A."),
       ("1er épisode provoqué, sans facteur persistant : ACO raccourci à 6 semaines.", "Durée."),
       ("≥ 3 mois si idiopathique, facteur persistant, récidive ou cancer.", "Prolongation."),
       ("AOD de référence ; HBPM/fonda possibles en initial.", "Moyens."),
       ("Alitement strict de 3 semaines pour éviter l’EP.", "Lever précoce.")],
      ["A", "B", "C", "D"],
      "Distale objectivée = ACO. 6 semaines si 1er épisode provoqué ; ≥ 3 mois sinon. Lever précoce."),
    Q("226", "B",
      "Concernant les thromboses veineuses superficielles, indiquer la ou les proposition(s) exacte(s).",
      [("L’EDV confirme, localise, cherche une TVP (~10 %) et le caractère variqueux.", "Rôle."),
       ("Sur veines saines : cancer, Buerger, Behçet, hémopathie, auto-immunité, thrombophilie.", "TVS non variqueuse."),
       ("Pas d’AINS généraux ni d’ACO curatif de 1re intention, sauf TVS étendue à la jonction saphéno-fémorale.", "Ce qui n’est pas recommandé."),
       ("Fondaparinux prophylactique 6 semaines (CALISTO) suggéré.", "Étude."),
       ("Toute TVS impose fibrinolyse et filtre cave.", "Hors sujet.")],
      ["A", "B", "C", "D"],
      "TVS : EDV (10 % de TVP). Compression ± fonda 6 sem. Curatif/chirurgie si jonction SF."),
    Q("226", "A",
      "Concernant la prévention de la MTEV, indiquer la ou les proposition(s) exacte(s).",
      [("L’aspirine n’est pas indiquée en prévention de la MTEV.", "Phrase explicite."),
       ("Voyage > 6 h : hydratation, contractions des mollets, vêtements non serrés ; si FDR, chaussettes classe 2–3 ± HBPM avant le départ.", "Voyage."),
       ("Médical : énoxaparine 0,4 mL/24 h SC ou fondaparinux 2,5 mg/24 h.", "Posologies."),
       ("Ortho lourde (PTH) : 4–6 semaines ; PTG : 10–15 jours ; énoxa, fonda ou AOD selon protocoles.", "Durées."),
       ("Toute hospitalisation médicale impose une fibrinolyse préventive à dose pleine.", "Prévention = HBPM/fonda prophylactiques.")],
      ["A", "B", "C", "D"],
      "Pas d’aspirine préventive. Voyage : mesures mécaniques ± HBPM. Médical : énoxa 0,4 ou fonda 2,5. Ortho : 4–6 sem (hanche)."),
    Q("226", "B",
      "Concernant le bilan de thrombophilie après MTEV, indiquer la ou les proposition(s) exacte(s).",
      [("Pas de bilan constitutionnel systématique après un 1er épisode, ni après 50 ans.", "Non-prescription."),
       ("Suggéré avant 50 ans si 1er épisode proximal/EP non provoqué + ATCD familial au 1er degré, si récidives, ou site atypique.", "Indications."),
       ("À 3–6 mois, AOD arrêtés 72 h : AT, PC, PS, FV Leiden, FII G20210A.", "Timing et panel."),
       ("Héparine perturbe AT et lupique ; AVK perturbent PC/PS ; AOD perturbent circulants et inhibiteurs.", "Interférences."),
       ("Prélever le bilan à J0 sous héparine pour décider d’une fibrinolyse.", "À distance, pas sous héparine, et cela ne guide pas la fibrinolyse.")],
      ["A", "B", "C", "D"],
      "Pas de thrombophilie systématique ni après 50 ans. Ciblée si jeune/familial/récidive/site atypique. À 3–6 mois."),
    Q("226", "A",
      "Homme de 55 ans, dyspnée brutale et douleur pleurale. ECG : tachycardie sinusale, S1Q3, T− de V1 à V4. GDS : hypoxémie-hypocapnie. Radio peu spécifique. Indiquer la ou les proposition(s) exacte(s).",
      [("Dans 90 % des cas, l’EP est suspectée devant dyspnée, douleur thoracique ou syncope.", "Triade."),
       ("ECG : TS, S1Q3, BBD, T− V1–V4 (piège SCA par ischémie du VD).", "Signes droits."),
       ("GDS normale dans 20 % des cas ; quasiment plus pratiquée sauf SpO2 < 90 % en air.", "Limites."),
       ("Radio normale n’élimine pas l’EP (atélectasie en bande, pleurésie, coupole, infarctus triangulaire).", "Aspécifique."),
       ("Ces examens de routine suffisent à confirmer l’EP sans imagerie ni scores.", "Orientation seulement.")],
      ["A", "B", "C", "D"],
      "Clinique + ECG droit + GDS inconstante + radio aspécifique = suspicion, pas preuve. 20–30 % d’EP spontanées."),
    Q("226", "A",
      "Jambe bleue, très douloureuse, œdémateuse, cyanosée, signes d’ischémie. Indiquer la ou les proposition(s) exacte(s).",
      [("Phlegmatia cerulea (phlébite bleue), rare mais grave.", "Définition."),
       ("Ischémie par obstruction extensive, œdème compressif et spasme.", "Mécanisme."),
       ("Un état de choc est possible.", "Mention."),
       ("Thrombolytiques non recommandés en 1re intention dans une TVP, sauf sauvetage de membre (phlegmatia/syndrome obstructif sévère).", "Exception."),
       ("Compression classe 3 seule, sans anticoagulation.", "La phlegmatia est une CI à la compression ; l’ACO s’impose.")],
      ["A", "B", "C", "D"],
      "Phlegmatia cerulea : ischémie sur TV extensive, CI à la compression. Thrombolyse veineuse seulement en sauvetage de membre."),
    Q("226", "B",
      "Concernant HERDOO2 et certaines durées (tableau 19.3), indiquer la ou les proposition(s) exacte(s).",
      [("HERDOO2 (femme) : signes de TVP, D-dimères > 250 µg/L, IMC > 30, âge > 65 ans.", "Items."),
       ("Femme, 1er épisode non provoqué par un facteur majeur et HERDOO2 < 1, ou femme < 50 ans : 3–6 mois.", "Ligne faible."),
       ("SAPL : anticoagulation non limitée par AVK (INR 2–3).", "Risque élevé."),
       ("La préférence du patient peut entrer dans la décision de durée.", "Rang A."),
       ("Un HERDOO2 élevé chez l’homme autorise l’arrêt à 6 semaines d’une EP proximale.", "Score féminin ; 6 semaines n’est pas la durée d’une EP.")],
      ["A", "B", "C", "D"],
      "HERDOO2 = femme. Aide à limiter à 3–6 mois si score bas. SAPL : AVK au long cours."),
    Q("226", "A",
      "EP confirmée, femme 48 ans, sPESI = 0, rein normal, pas de saignement, bon entourage. Indiquer la ou les proposition(s) exacte(s).",
      [("Hospitalisation de règle, mais discutable si PESI/sPESI = 0 et pas d’autre facteur d’hospit.", "Bas risque."),
       ("Ambulatoire : diagnostic de certitude, éducation, surveillance organisée, évaluation des risques.", "Conditions."),
       ("On n’hospitalise jamais une EP, même iliocave ou en IR sévère.", "On hospitalise IR sévère, haut risque hémorragique, TVP iliocave, mauvais environnement."),
       ("sPESI ≥ 1 ≈ 10 % de mortalité ; + souffrance VD → USIC + ACO (intermédiaire haut).", "Filière Points."),
       ("sPESI = 0 impose fibrinolyse et filtre cave avant le retour à domicile.", "Bas risque = ACO ± ambulatoire.")],
      ["A", "B", "D"],
      "sPESI = 0 : ACO, séjour court ou ambulatoire si logistique OK. Hospitaliser IR, hémorragie, iliocave. Pas de fibrinolyse."),
    Q("226", "A",
      "Scintigraphie V/Q et ETT hors choc : indiquer la ou les proposition(s) exacte(s).",
      [("EP : mismatch (perfusion défaillante, ventilation conservée).", "Principe."),
       ("Compte rendu en 3 niveaux : élevée, non diagnostique, normale.", "Standard."),
       ("Scinti normale + score clinique faible : on peut exclure l’EP.", "Règle."),
       ("Hors choc, un cœur pulmonaire aigu à l’ETT classe le patient à risque intermédiaire.", "Pronostic."),
       ("Une pathologie cardiorespiratoire chronique améliore la performance de la scintigraphie.", "Elle la limite.")],
      ["A", "B", "C", "D"],
      "V/Q : mismatch, 3 niveaux ; normale + clinique faible = exclusion. Moins fiable si poumon chronique. ETT : stratification."),
    Q("226", "A",
      "Avant d’arrêter un anticoagulant après une EP, indiquer la ou les proposition(s) exacte(s).",
      [("Toujours éliminer une HTP post-embolique.", "Rang A."),
       ("HTP-TEC chez 0,5–5 % des traités ; endartériectomie = traitement de choix en centre expert.", "Chiffres + ttt."),
       ("EDV de fin de traitement pour les séquelles de TVP.", "Suivi."),
       ("Pas d’imagerie de routine pendant le ttt, sauf HTAP initiale (contrôle PAP par ETT).", "Indication ciblée."),
       ("Une scintigraphie mensuelle pendant 2 ans est obligatoire avant tout arrêt.", "Pas de suivi d’imagerie systématique.")],
      ["A", "B", "C", "D"],
      "Avant l’arrêt : éliminer l’HTP-TEC. ETT si HTAP initiale, EDV de séquelles. Deux tiers reperfusent."),
    Q("226", "A",
      "Posologies parentérales curatives (HBPM, fondaparinux) : indiquer la ou les proposition(s) exacte(s).",
      [("Énoxaparine 1 mg/kg/12 h ; tinzaparine 175 UI/kg/24 h (AMM EP ± TVP).", "AMM."),
       ("Daltéparine 100 UI/kg/12 h ; nadroparine 85 UI/kg/12 h ou 171 UI/kg/24 h.", "Autres HBPM."),
       ("Fondaparinux 7,5 mg/24 h si poids 50–100 kg, sans anti-Xa systématique.", "Fonda."),
       ("Anti-Xa HBPM seulement si risque d’accumulation (IR modérée, âge, petit poids, obésité), à H4.", "Surveillance ciblée."),
       ("Surveillance plaquettaire systématique sous fondaparinux, comme sous HNF.", "Pas de plaquettes de routine sous fonda.")],
      ["A", "B", "C", "D"],
      "Curatif : énoxa 1 mg/kg/12 h, tinza 175/j, fonda 7,5 mg (50–100 kg). Anti-Xa HBPM seulement si accumulation."),
    Q("226", "A",
      "Histoire naturelle et SPT : indiquer la ou les proposition(s) chiffrée(s) exacte(s).",
      [("Contention initiale ≥ 3 mois : −50 % de SPT.", "Chiffre."),
       ("SPT en moyenne dans les 2 premières années.", "Délai."),
       ("Sans ACO, 50 % des MTEV symptomatiques récidivent en 3 mois ; à 1 an : 9 % si non provoquée vs 3 % si provoquée.", "Récidive."),
       ("EP dans les 3–7 jours après une TVP ; mortelle dès la 1re heure dans 10 % des cas.", "Chronologie."),
       ("Une TVP distale asymptomatique postopératoire s’étend en proximal dans ~80 % des cas, toujours avec EP clinique.", "Extension ~20 %, rarement pulmonaire.")],
      ["A", "B", "C", "D"],
      "Contention précoce −50 % de SPT. Sans ACO : 50 % de récidive à 3 mois. EP à J3–J7, 10 % mortelle d’emblée."),
    Q("226", "A",
      "Thrombus mobile dans les cavités droites au cours d’une EP. Indiquer la ou les proposition(s) exacte(s).",
      [("Haut risque de mortalité précoce, surtout si mobile.", "Forme particulière."),
       ("Traitement urgent ; place relative thrombolyse vs embolectomie encore mal validée.", "Incertitude."),
       ("L’ETT peut exceptionnellement voir un thrombus des gros troncs pulmonaires.", "Signe rare."),
       ("Embolies non cruoriques : septique, gazeuse, graisseuse, amniotique, tumorale — ttt étiologique.", "EP non thrombotique."),
       ("Si sPESI = 0, abstention thérapeutique possible.", "Traitement urgent, pas d’abstention.")],
      ["A", "B", "C", "D"],
      "Thrombus droit mobile = urgence. Penser aussi aux EP non fibrinocruoriques."),
]

# =============================================================================
# 235 Péricardite (12) — évite lot1 : diag positif, ECG 4 stades, facteurs majeurs,
# tamponnade déf, ttt bénigne, étiologies/évolution générales
# =============================================================================
questions += [
    Q("235", "B",
      "Un patient a un frottement à J4 d’un IDM transmural reperméabilisé. Un autre, 8 semaines après IDM, a fièvre, péricardite, pleurésie, arthralgies et QT long. Indiquer la ou les proposition(s) exacte(s).",
      [("Péricardite précoce J3–J5 après IDM transmural, évolution le plus souvent favorable.", "Forme précoce."),
       ("Péricardite tardive (2e–16e semaine) = Dressler : fièvre, péricarde, plèvre, arthralgies, AEG, inflammation, QT long.", "Dressler."),
       ("Le Dressler est devenu rare depuis la reperfusion précoce.", "Historique."),
       ("Toute péricardite à J4 d’IDM impose une fibrinolyse itérative.", "Pas de fibrinolyse ; les thrombolytiques sont même CI en péricardite aiguë."),
       ("Syndrome post-péricardiotomie : jours à mois après chirurgie/greffe ; la chirurgie cardiaque est la 1re cause actuelle de constriction.", "Postop.")],
      ["A", "B", "C", "E"],
      "Deux péricardites post-IDM : précoce J3–J5 et Dressler tardif (rare depuis la reperfusion). Post-péricardiotomie = 1re cause de constriction."),
    Q("235", "A",
      "Concernant l’ETT et la radio d’une péricardite, indiquer la ou les proposition(s) exacte(s).",
      [("L’ETT peut être normale (péricardite sèche).", "Fréquent."),
       ("Abondance : < 10 mm minime, 10–20 mm modéré, > 20 mm abondant.", "Grades."),
       ("Elle apprécie topographie et tolérance, et confirme une tamponnade.", "Rôle."),
       ("Radio souvent normale ; rectitude du bord gauche ou cœur en carafe si gros épanchement.", "Radio."),
       ("Un épanchement minime suffit à lui seul, sans autre critère, à porter le diagnostic.", "Il faut 2 critères parmi douleur, frottement, ECG, épanchement.")],
      ["A", "B", "C", "D"],
      "ETT parfois normale. Grades <10 / 10–20 / >20 mm. Carafe si abondant. L’épanchement n’est qu’un des 4 critères."),
    Q("235", "A",
      "Outre les 4 facteurs majeurs ESC 2015, quels facteurs mineurs peuvent faire discuter une hospitalisation ?",
      [("Immunodépression.", "Mineur."),
       ("Traitement anticoagulant.", "Risque d’hémopéricarde."),
       ("Suites d’un traumatisme thoracique.", "Mineur."),
       ("Myocardite associée (troponine élevée ± trouble de cinétique).", "Mineur."),
       ("Un fébricule à 37,8 °C chez un jeune, sans autre anomalie, impose USIC et drainage.", "Majeur = fièvre > 38 °C ; drainage = tamponnade.")],
      ["A", "B", "C", "D"],
      "Mineurs : immunodépression, ACO, traumatisme, myocardite. Un fébricule < 38 °C n’impose ni USIC ni drainage."),
    Q("235", "A",
      "Quelles sont les indications d’une ponction ou d’un drainage péricardique ?",
      [("Tamponnade.", "Indication vitale."),
       ("Forte suspicion néoplasique.", "But étiologique."),
       ("Épanchement abondant symptomatique malgré 1 semaine de ttt médical bien conduit.", "Résistance."),
       ("Suspicion purulente : drainage chirurgical à privilégier.", "Voie chir."),
       ("Ponction systématique de toute forme virale typique pour PCR de routine.", "Inutile dans les formes typiques non graves.")],
      ["A", "B", "C", "D"],
      "Ponction : tamponnade, néoplasie, épanchement abondant résistant à J7. Chirurgical si purulent."),
    Q("235", "B",
      "Concernant la péricardite constrictive, indiquer la ou les proposition(s) exacte(s).",
      [("Constriction modérée dans < 10 % des cas, par péricarde fibreux ou fibrocalcaire.", "Incidence."),
       ("Adiastolie avec égalisation des pressions télédiastoliques des 4 cavités ; dip-plateau au cathétérisme droit.", "Hémodynamique."),
       ("IC droite souvent prédominante (TJ, ascite) ; DD : cardiomyopathie restrictive.", "Clinique."),
       ("Traitement parfois chirurgical (péricardectomie).", "TTT."),
       ("Des corticoïdes à forte dose dès J1 d’une péricardite virale préviennent toujours la constriction.", "Corticoïdes non indiqués en 1re intention (récidives).")],
      ["A", "B", "C", "D"],
      "Constriction < 10 % : adiastolie, dip-plateau, IC droite. Péricardectomie. Pas de corticoïdes préventifs de routine."),
    Q("235", "B",
      "Concernant la péricardite purulente, indiquer la ou les proposition(s) exacte(s).",
      [("Rare mais grave ; staphylocoque, pneumocoque, streptocoque, BGN.", "Germes."),
       ("Terrain : immunodéprimé, septicémie, pleuropneumopathie, postop cardiaque/thoracique.", "Contexte."),
       ("Tamponnade fréquente, constriction possible.", "Évolution."),
       ("ATB adaptée au germe du liquide ; drainage chirurgical souvent nécessaire.", "PEC."),
       ("Ibuprofène seul 3 jours en ambulatoire est le standard.", "Urgence médico-chirurgicale.")],
      ["A", "B", "C", "D"],
      "Purulente : rare, grave, immunodéprimé/postop. ATB + drainage chirurgical."),
    Q("235", "B",
      "Concernant la péricardite tuberculeuse, indiquer la ou les proposition(s) exacte(s).",
      [("Subaiguë liquidienne, AEG, fièvre persistante ; terrain : TB, âge, greffe, VIH, alcool.", "Clinique."),
       ("IDR faussement négative dans près d’un tiers des cas ; radio pulmonaire souvent anormale.", "Limites."),
       ("ADA élevée, PCR et cultures (tubage, expectoration, liquides) aident au diagnostic.", "Outils."),
       ("Antituberculeux ; corticoïdes parfois pour diminuer le risque de constriction.", "PEC."),
       ("Tamponnade et constriction sont exceptionnelles, ce qui autorise l’abstention d’antituberculeux.", "Complications fréquentes ; ttt indispensable.")],
      ["A", "B", "C", "D"],
      "TB : subaiguë, AEG, VIH/alcool. ADA/PCR/cultures. Antituberculeux ± corticoïdes."),
    Q("235", "B",
      "Cancer bronchique et tamponnade. Indiquer la ou les proposition(s) exacte(s) sur la péricardite néoplasique.",
      [("Métastases 40 fois plus fréquentes que le mésothéliome ; sources : bronche, sein, mélanome, leucémies, lymphomes, Kaposi.", "Épidémio."),
       ("Épanchement souvent hémorragique ; tamponnade fréquente → ponction urgente.", "Présentation."),
       ("Cytologie ou biopsie essentielles ; TDM/IRM parfois utiles.", "Preuve."),
       ("Récidive fréquente : suivi clinique et ETT.", "Évolution."),
       ("Colchicine 3 mois sans drainage est le ttt unique de la tamponnade néoplasique.", "La tamponnade se draine.")],
      ["A", "B", "C", "D"],
      "Néoplasique : secondaires (poumon, sein, mélanome, hémopathies), hémorragique, tamponnade. Drainage + preuve cyto."),
    Q("235", "A",
      "Sportif de 26 ans : douleur rétrosternale majorée en décubitus, calmée penché en avant, résistante à la TNT, après une virose. Indiquer la ou les proposition(s) exacte(s).",
      [("Sémiologie typique de péricardite.", "Clinique."),
       ("SCA, EP et dissection restent à évoquer d’emblée.", "Différentiel vital."),
       ("Frottement systolodiastolique variable (« cuir neuf ») : confirme mais son absence n’élimine pas.", "Inconstant."),
       ("Réponse à 1 g d’aspirine, CRP élevée et minime décollement confortent, sans dispenser d’un ECG répété.", "Vignette du livre."),
       ("Un sus-ST territorialisés avec miroir, trinitrino-sensible, oriente vers une péricardite plutôt qu’un SCA.", "Profil du SCA, pas de la péricardite.")],
      ["A", "B", "C", "D"],
      "Douleur positionnelle TNT-résistante. Différentiel SCA/EP/dissection. Le sus-ST en miroir n’est pas une péricardite."),
    Q("235", "B",
      "Échec AINS + colchicine : corticoïdes et interactions. Indiquer la ou les proposition(s) exacte(s).",
      [("Corticoïdes non indiqués en 1re intention (risque de récidive).", "Notion inacceptable."),
       ("Si échec : prednisone 0,25–0,5 mg/kg/j, en poursuivant la bithérapie.", "Dose ESC."),
       ("Interactions CYP3A4 : macrolides, ciclosporine, vérapamil, statines ; surveiller ASAT, créatinine, CPK, NFS.", "PV."),
       ("Diarrhée : baisser la dose ; arrêt progressif la dernière semaine à 0,5 mg 1 j/2.", "Sevrage."),
       ("Pas de limite de dose en IR terminale.", "CI en IR sévère ; demi-dose si DFG < 35, âge > 70 ou poids < 70 kg.")],
      ["A", "B", "C", "D"],
      "Pas de corticoïdes d’emblée. Si échec : 0,25–0,5 mg/kg/j. Colchicine : CYP3A4, CI IR sévère."),
    Q("235", "A",
      "Quel suivi après une péricardite aiguë bénigne ?",
      [("J7 (MT), M1 (cardiologue + ETT), M3 et M6.", "Calendrier."),
       ("Vérifier symptômes, CRP, ETT, et gérer l’arrêt progressif.", "Objectifs."),
       ("Une fois la douleur calmée, le sport de compétition peut reprendre dès J3, sans contrôle de CRP ni d’ETT.", "Repos jusqu’à disparition des symptômes et normalisation CRP, ECG et ETT (en général le 1er mois)."),
       ("Récidive souvent par ttt trop court, entre 3 mois et 3 ans ; la colchicine la prévient.", "Prévention."),
       ("Coronarographie systématique à J7 chez tout sujet jeune à ETT normale.", "Pas d’indication.")],
      ["A", "B", "D"],
      "Suivi J7 / M1 (ETT) / M3 / M6. Sport après normalisation CRP/ECG/ETT. Colchicine anti-récidive."),
    Q("235", "A",
      "Homme de 62 ans sous AVK, dyspnéique, PAS 82 mmHg, TJ, bruits assourdis, pouls paradoxal. Radio en carafe, microvoltage, alternance électrique. Indiquer la ou les proposition(s) exacte(s) de PEC.",
      [("USIC : tamponnade = urgence, risque d’arrêt par adiastolie.", "Filière."),
       ("Remplissage par macromolécules ; discuter arrêt/neutralisation des ACO.", "Attente."),
       ("Ponction écho-guidée ou drainage ; ETT : collapsus droit, septum paradoxal inspiratoire, swinging heart.", "Geste."),
       ("Contextes : néoplasie, traumatisme, TB, hémopéricarde ; exceptionnelle dans la forme virale.", "Étiologies."),
       ("Nitrés IV et furosémide 1 mg/kg comme dans un OAP.", "Choc obstructif : remplissage + drainage, pas de déplétion.")],
      ["A", "B", "C", "D"],
      "Tamponnade : USIC, remplissage, stop ACO, drainage. Pas de nitrés/diurétiques d’OAP."),
]

# =============================================================================
# 331 ACR (14) — évite lot1 : déf no-flow/low-flow, chaîne, diag témoin, BLS ACD,
# rythmes/CEE, étiologies générales, pronostic préhosp général, ventilation/DEA
# =============================================================================
questions += [
    Q("331", "A",
      "0 h 30, USIC, homme 54 ans J1 de primaire d’IDM, inconscient. Scope : FV ; MCE déjà commencé. Indiquer la ou les proposition(s) exacte(s).",
      [("ACR par FV ; no-flow quasi nul si MCE immédiat.", "Vignette du livre."),
       ("Traitement immédiat : CEE, seul ttt efficace de la FV.", "Rythme chocable."),
       ("Cause la plus probable : ischémique (SCA récent).", "1re étiologie."),
       ("ROSC en 3 min : pronostic neuro bien meilleur qu’après 10 min de no-flow.", "Déterminant."),
       ("On attend un ECG 12 dérivations avant le premier choc.", "CEE immédiat.")],
      ["A", "B", "C", "D"],
      "FV post-IDM en USIC : CEE immédiat, no-flow minime, cause ischémique."),
    Q("331", "B",
      "Concernant l’adrénaline en RCP médicalisée, indiquer la ou les proposition(s) exacte(s).",
      [("1 mg / 4 min, IV ou endotrachéal.", "Posologie."),
       ("Incontournable en asystolie ; en FV/TV persistante, après 2 min de RCP, juste avant le 2e ou 3e choc.", "Séquence."),
       ("Au-delà de 1–2 mg cumulés, survie faible et survie sans séquelle lourde quasi nulle.", "Pronostic lié à la dose."),
       ("Effet utile surtout alpha ; effets bêta controversés.", "Pharmacologie."),
       ("Elle remplace MCE et CEE en FV : on l’injecte d’abord.", "MCE et CEE restent prioritaires.")],
      ["A", "B", "C", "D"],
      "Adrénaline 1 mg/4 min. Asystolie ; en FV avant le 2e–3e choc. Jamais un substitut du massage/choc."),
    Q("331", "B",
      "Amiodarone et autres antiarythmiques de RCP : indiquer la ou les proposition(s) exacte(s).",
      [("Amiodarone 300 mg dans 20–30 mL de NaCl, rapidement, juste avant le 3e choc si TV/FV réfractaire.", "Dose/timing."),
       ("Reboost 150 mg si persistante après le 3e CEE ou récidivante.", "Reboost."),
       ("Lidocaïne seulement si pas d’amiodarone : 1,5 mg/kg, total ≤ 3 mg/kg.", "Alternative."),
       ("MgSO4 2 g IVD si torsades ou suspicion d’hypomagnésémie.", "Indication."),
       ("L’amiodarone 300 mg se substitue au premier CEE en FV.", "Le 1er geste est le choc.")],
      ["A", "B", "C", "D"],
      "Amiodarone 300 mg avant le 3e choc, puis 150 mg. Lidocaïne si pas d’amio. Mg 2 g si torsades."),
    Q("331", "A",
      "Énergie des chocs et DSA : indiquer la ou les proposition(s) exacte(s).",
      [("Biphasique jusqu’à 200 J, plus sûr/efficace que le monophasique 360 J.", "Énergies."),
       ("Survie FV : 40–60 % si CEE à 1–3 min, 35 % à 4–6 min, 25 % à 7–10 min ; < 5 % au-delà de 10 min.", "Délai."),
       ("Premier CEE idéalement dans les 3 minutes.", "Objectif."),
       ("Le DSA n’envoie un choc que si le rythme est chocable.", "Sécurité."),
       ("Un DSA choque d’emblée toute asystolie, sans analyse.", "L’asystolie n’est pas chocable.")],
      ["A", "B", "C", "D"],
      "Biphasique ≤ 200 J. Chaque minute compte. DSA : analyse puis choc si FV/TV. Jamais de choc d’asystolie."),
    Q("331", "A",
      "ACR réfractaire et limites éthiques : indiquer la ou les proposition(s) exacte(s).",
      [("Définition française discutée : pas de ROSC après 30 min de RCP médicale bien conduite.", "Définition."),
       ("Hors hypothermie, no-flow > 10 min : licite de s’interroger sur l’éthique de la réanimation.", "Seuil."),
       ("Si no-flow bref, un low-flow long mais de qualité peut encore permettre une récupération.", "Hiérarchie."),
       ("Arrêt de réanimation collégial, orienté par un algo de neuropronostication.", "Points."),
       ("Au-delà de 5 min de no-flow, la survie sans séquelle reste > 50 % dans toutes les séries.", "Survie 7–8 % après 5 min, ~0 % après 10 min.")],
      ["A", "B", "C", "D"],
      "Réfractaire ≈ 30 min sans ROSC. No-flow > 10 min : question éthique. Arrêt collégial."),
    Q("331", "A",
      "ROSC chez un homme de 62 ans qui avait une douleur thoracique ; ECG : sus-ST. Indiquer la ou les proposition(s) exacte(s).",
      [("Coronarographie ± angioplastie si SCA avéré ou suspecté (douleur, sus-ST, BBG).", "Reco post-ACR."),
       ("< 30 ans : coronaire rare → TV non ischémique, congénitales.", "Âge."),
       ("Un ROSC n’est pas synonyme de survie ni de récupération neurologique.", "Point."),
       ("5e maillon : O2, éviter hypoxie/hypercapnie, contrôler glycémie et température.", "Post-resuscitation care."),
       ("Toute coronarographie est contre-indiquée dans les 24 h post-ROSC, même en sus-ST.", "C’est précisément l’indication.")],
      ["A", "B", "C", "D"],
      "Post-ROSC : coro si SCA (surtout sus-ST). Soins : O2, PaCO2, glycémie, thermie. ROSC ≠ survie."),
    Q("331", "A",
      "Préservation cérébrale après ACR : indiquer la ou les proposition(s) exacte(s).",
      [("L’hyperthermie aggrave l’ischémie-reperfusion : la prévenir (contrôle thermique).", "Message fort."),
       ("Hypothermie ~34 °C : place encore débattue.", "Cooling."),
       ("Lutter contre l’hyperglycémie ; sédation pour baisser la consommation d’O2.", "Métabo/sédation."),
       ("Neuropronostic : Glasgow, EEG, PES, répétés entre J1 et J3.", "Encadré 21.4."),
       ("Hypercapnie et hypoxie sont recherchées pour vasodilater le cerveau.", "Elles entraînent une HIC fatale.")],
      ["A", "B", "C", "D"],
      "Cerveau : éviter hyperthermie, hyperglycémie, hypoxie, hypercapnie. Neuropronostic J1–J3."),
    Q("331", "A",
      "Après ROSC, FEVG transitoirement très altérée. Indiquer la ou les proposition(s) exacte(s) sur la sidération.",
      [("Favorisée par no-flow/low-flow prolongés, fortes doses de vasopresseurs, nombre et intensité des CEE.", "Facteurs."),
       ("Dobutamine = ttt de choix des troubles de contractilité.", "Inotrope."),
       ("Assistance (ECMO, décharge VG) si dobutamine insuffisante.", "Escalade."),
       ("Monitoring ETT ± pressions invasives.", "Surveillance."),
       ("La sidération contre-indique toute coronarographie, même en sus-ST.", "La coro pour SCA n’est pas CI.")],
      ["A", "B", "C", "D"],
      "Sidération : no-flow, adrénaline, chocs. Dobutamine ± assistance. La coro pour SCA reste indiquée."),
    Q("331", "B",
      "ACR intrahospitalier sur BAV 3 sans pouls. Indiquer la ou les proposition(s) exacte(s).",
      [("Atropine et isoprénaline : seulement si étiologie conductive ou vagale maligne, en milieu médicalisé.", "Cadre."),
       ("Atropine 1 mg / 3–5 min, total 0,04 mg/kg, si bradycardie sinusale extrême.", "Posologie."),
       ("Isoprénaline : 5 amp. 0,2 mg dans 250 mL G5 %, cible FC ≥ 50–60/min, utile dans le BAV 3.", "Préparation."),
       ("Asystolie vraie : MCE + adrénaline, pas de CEE.", "Non chocable."),
       ("L’atropine 1 mg remplace le massage tant que le BAV n’est pas résolu.", "MCE prioritaire tant qu’il n’y a pas de pouls.")],
      ["A", "B", "C", "D"],
      "BAV/bradycardie : atropine, isoprénaline, toujours sur un MCE sans pouls. Asystolie : pas de choc."),
    Q("331", "B",
      "RCP SMUR : indiquer la ou les proposition(s) exacte(s).",
      [("Compressions de qualité, interruptions minimales ; intubation ≤ 30 s.", "Encadré 21.3."),
       ("O2 dès que possible, capnographe (EtCO2), VVP ± artérielle.", "Monitoring."),
       ("Si intubation difficile : ventilation au masque plutôt que d’interrompre longtemps le MCE.", "Priorité circulation."),
       ("Discuter ECMO ; préparer le ttt étiologique (intoxication, revascularisation).", "Escalade."),
       ("Interrompre le MCE 2 min toutes les 30 s pour palper le pouls radial.", "Interruptions à minimiser.")],
      ["A", "B", "C", "D"],
      "SMUR : MCE de qualité, EtCO2, O2, VVP, intubation courte ou masque, étiologie, ECMO."),
    Q("331", "B",
      "Bicarbonate et thrombolyse préhospitalière : indiquer la ou les proposition(s) exacte(s).",
      [("Acidose et hyperK dès 3–4 min d’ACR.", "Désordres."),
       ("Bicarbonate : pas d’amélioration claire de survie ; réservé aux RCP prolongées, hyperK, acidose préalable, toxiques (tricycliques, phénobarbital).", "Indications restreintes."),
       ("Thrombolyse préhosp non recommandée en routine ; cas par cas si IDM ou EP massive avérés/fortement suspectés.", "Position."),
       ("20–40 % des ACR compliquent un IDM ; jusqu’à ~70 % des ACR extra-hospitaliers réanimés auraient un IDM ou une EP massive.", "Chiffres."),
       ("Tout ACR extra-hospitalier reçoit une thrombolyse pleine dose avant le 1er CEE.", "Non recommandé, et jamais avant le CEE d’une FV.")],
      ["A", "B", "C", "D"],
      "Bicarbonate non routinier. Thrombolyse préhosp au cas par cas IDM/EP massive."),
    Q("331", "A",
      "Épidémiologie chiffrée de l’ACR dans ce chapitre : indiquer la ou les proposition(s) exacte(s).",
      [("France : ~40 000 décès/an, incidence 0,75 ‰.", "Intro."),
       ("Survie sans séquelle 2–4 % ; survie des arrêts intra-hospitaliers 40–50 %.", "Contraste."),
       ("Survie −10 % par minute sans RCP.", "Pente."),
       ("ILCOR : 2–10 % sortent pour une vie normale dans les villes bien équipées en DSA.", "Fourchette."),
       ("En France, 80 % de la population est formée à la RCP.", "Seulement 10–15 % ; maillons publics encore faibles.")],
      ["A", "B", "C", "D"],
      "40 000 morts/an. Survie sans séquelle 2–4 %, −10 %/min sans RCP. Formation grand public 10–15 %."),
    Q("331", "A",
      "Témoin formé, MCE à 100/min, DSA apporté. Quelles précisions techniques sont exactes ?",
      [("Amplitude 4–5 cm ; relais toutes les 2 min.", "Paramètres."),
       ("Après un choc DSA : 2 min de RCP avant de vérifier la circulation.", "Post-choc."),
       ("Pas de bouche-à-bouche chez l’adulte (cause souvent rythmique) ; essentiel chez l’enfant (cause souvent hypoxique).", "Différence d’âge."),
       ("Canule de Guedel dès que les secours/le milieu médicalisé le permettent.", "Airway."),
       ("Compressions de 1 cm à 40/min pour éviter les fractures de côtes.", "Cible 4–5 cm à 100/min.")],
      ["A", "B", "C", "D"],
      "MCE 4–5 cm, 100/min, relais 2 min. Post-choc : 2 min de RCP. Pas de bouche-à-bouche adulte."),
    Q("331", "A",
      "50 % des FV se dégradent en asystolie entre la 4e et la 8e minute. Indiquer la ou les conséquence(s) exacte(s).",
      [("L’asystolie marque souvent un arrêt déjà ancien, de mauvais pronostic.", "Dégradation."),
       ("Au début de la RCP, une FV n’est vue que dans 40–70 % des cas selon la rapidité.", "Prévalence."),
       ("ILCOR 2015 : rythme initial le plus fréquent encore une FV (70–80 %) ; 15–20 % de bradycardie/asystolie.", "Répartition."),
       ("DEM : poursuivre le MCE malgré une activité électrique, sans mécanique efficace.", "PEA."),
       ("Toute asystolie se choque à 360 J avant tout massage.", "Asystolie : massage, pas de CEE.")],
      ["A", "B", "C", "D"],
      "FV → asystolie avec le temps. Asystolie et DEM se massent, elles ne se choquent pas."),
]

# =============================================================================
# 330 Antithrombotiques (16) — évite lot1 : AOD vs AVK, relais, AOD généralités,
# posologies tableau, aspirine DAPT, héparines général, TIH général, accidents antidotes
# =============================================================================
questions += [
    Q("330", "A",
      "SCA stenté, homme 68 ans, 82 kg, sans AVC. Indiquer la ou les proposition(s) exacte(s) sur prasugrel et ticagrélor.",
      [("Prasugrel : charge 60 mg puis 10 mg/j, SCA angioplasté, âge < 75 ans.", "Indication."),
       ("CI absolue du prasugrel : ATCD d’AVC ; CI relatives : poids < 60 kg, âge > 75 ans.", "CI."),
       ("Ticagrélor : charge 180 mg puis 90 mg × 2/j ; EI principal : dyspnée (18 %).", "Posologie/EI."),
       ("Inhibition P2Y12 plus rapide et plus forte que le clopidogrel (70–80 % vs 40–50 %).", "Puissance."),
       ("Le prasugrel est l’anti-P2Y12 de choix après fibrinolyse et après un AVC.", "Post-fibrinolyse : clopidogrel ; AVC = CI du prasugrel.")],
      ["A", "B", "C", "D"],
      "Prasugrel 60 puis 10 (CI AVC). Ticagrélor 180 puis 90×2 (dyspnée 18 %). Plus puissants que le clopidogrel."),
    Q("330", "A",
      "Concernant le clopidogrel, indiquer la ou les proposition(s) exacte(s).",
      [("Prodrogue CYP2C19 ; 15–25 % de mauvais métaboliseurs.", "PGx."),
       ("Charge 300–600 mg puis 75 mg/j.", "Dose."),
       ("Angioplastie programmée et SCA si prasugrel/ticagrélor non indiqués, ou après fibrinolyse ; DAPT 3–12 mois.", "Place."),
       ("Pas de test biologique fiable de routine pour guider la dose.", "Surveillance."),
       ("Inhibiteur réversible de la COX-1, effet 24 h, arrêt la veille d’une chirurgie.", "Il bloque le P2Y12 ; l’aspirine est irréversible 7–10 j.")],
      ["A", "B", "C", "D"],
      "Clopidogrel : prodrogue CYP2C19, 300–600 puis 75, post-fibrinolyse. Pas un AINS COX."),
    Q("330", "A",
      "Patient sous warfarine (INR cible 2–3) : soins dentaires, puis plus tard chirurgie urologique. Indiquer la ou les proposition(s) exacte(s).",
      [("Geste à risque modéré (dents, petite chir, certaines biopsies) : souvent sans arrêter l’AVK, INR dans la fourchette basse.", "Règle 1."),
       ("Risque hémorragique plus élevé et risque thrombotique modéré (TVP/EP > 3 mois, FA bas risque) : arrêt 3–4 j, reprise le soir, sans relais.", "Arrêt simple."),
       ("Relais héparine si TVP/EP < 3 mois, FA à haut risque, ou valve mécanique.", "Haut risque thrombotique."),
       ("Les relais héparine sont source de complications hémorragiques et thrombotiques.", "Mise en garde."),
       ("Pour une valve mécanique, on remplace l’AVK par un AOD 48 h avant le geste.", "AOD CI sur valve mécanique.")],
      ["A", "B", "C", "D"],
      "Geste modéré : on maintient l’AVK. Geste à risque : arrêt court ou relais héparine si valve/EP récente/FA haut risque. Pas d’AOD sur valve."),
    Q("330", "A",
      "Thrombolytiques (item 330) : indications et surveillance. Indiquer la ou les proposition(s) exacte(s).",
      [("IDM < 6–12 h s’il n’y a pas d’angioplastie possible (Samu).", "Coronaire."),
       ("AVC ischémique < 4 h 30 après exclusion d’une hémorragie.", "Neuro."),
       ("EP grave.", "MTEV."),
       ("HIC 0,7–2 % ; groupage systématique ; tests de coag perturbés ~24 h.", "Risque."),
       ("La streptokinase reste le ttt de 1re intention en bolus oral.", "Plus commercialisée ; ténectéplase = bolus IV.")],
      ["A", "B", "C", "D"],
      "Fibrinolyse : IDM sans PCI, AVC < 4 h 30, EP grave. HIC 0,7–2 %. Ténectéplase en bolus IV."),
    Q("330", "A",
      "Quelles CI aux thrombolytiques figurent dans le collège ?",
      [("Allergie, coagulopathie/thrombopathie/thrombopénie sévère, ulcère < 6 mois.", "Hémorragie."),
       ("Chir générale < 10 j, chir vasculaire < 1 mois, traumatisme/ponction de gros vaisseaux, RCP prolongée.", "Trauma/chir."),
       ("HTA > 200 mmHg non contrôlée, AVC étendu < 6 mois, AVK, IH sévère.", "Tension/iatrogénie."),
       ("Péricardite aiguë, endocardite, grossesse, malformation vasculaire cérébrale.", "Cardio/obst."),
       ("Un SCA sus-ST de moins de 3 h sans PCI contre-indique la fibrinolyse.", "C’est une indication.")],
      ["A", "B", "C", "D"],
      "Nombreuses CI. L’IDM sans PCI est une indication, pas une CI."),
    Q("330", "A",
      "HNF IV, homme 70 kg, EP instable. Posologies du chapitre 330 : indiquer la ou les proposition(s) exacte(s).",
      [("Bolus 70–80 UI/kg (~5 000 UI) puis 18 UI/kg/h (~500 UI/kg/j, ~30 000 UI/24 h).", "Schéma 330."),
       ("TCA 2–3 × témoin et/ou anti-Xa 0,5–0,8 ; 1er TCA vers H5.", "Cibles 330."),
       ("TCA < 45 s : +6 000 UI/24 h + bolus 5 000 U ; TCA > 110 s : −6 000 et stop SAP 1 h.", "Tableau 22.5."),
       ("Demi-vie ~1 h 30 ; antidote = protamine IV, effet immédiat.", "PK."),
       ("Les HBPM se titrent par un INR cible 3,5, y compris en IR sévère.", "Pas d’INR pour les HBPM ; CI si ClCr < 30.")],
      ["A", "B", "C", "D"],
      "HNF 330 : bolus 70–80 UI/kg puis 18 UI/kg/h, TCA 2–3×, 1er contrôle H5, protamine."),
    Q("330", "A",
      "Warfarine, fluindione et grossesse : indiquer la ou les proposition(s) exacte(s).",
      [("Warfarine : AVK de référence ; 5 mg le soir J0–J2, 1er INR le matin de J4.", "Schéma d’approche."),
       ("Initiation de fluindione déconseillée (IR immunoallergique, surtout < 6 mois) ; on ne switch pas un patient longtemps équilibré.", "ANSM."),
       ("AVK tératogènes, CI dans la 1re partie du 1er trimestre.", "Grossesse."),
       ("Miconazole (Daktarin®) : coprescription strictement CI.", "Interaction."),
       ("L’acénocoumarol en 1 prise/j est l’AVK recommandé devant la warfarine.", "2 prises, non recommandé comme référence.")],
      ["A", "B", "C", "D"],
      "Warfarine 5 mg × 3 soirs, INR à J4. Plus d’initiation de fluindione. CI 1er trimestre et miconazole."),
    Q("330", "A",
      "Interactions des AOD et tests d’hémostase : indiquer la ou les proposition(s) exacte(s).",
      [("Interactions : macrolides, antiprotéases, azolés, certains anticancéreux, amiodarone, diltiazem, vérapamil ; AINS à éviter.", "Liste."),
       ("Les tests usuels sont perturbés : on ne s’en sert pas pour titrer l’effet.", "Message."),
       ("Dabigatran : TT très allongé ; anti-Xa très augmenté sous rivaroxaban/apixaban.", "Tableau 22.10."),
       ("Perturbent la recherche d’APL : les arrêter 2–3 j avant un bilan de thrombophilie avec APL.", "Lupique."),
       ("Un INR à 2,5 sous apixaban prouve que la dose est parfaitement adaptée.", "L’INR ne titre pas les AOD.")],
      ["A", "B", "C", "D"],
      "AOD : interactions (macrolides, azolés, amio, ICa). Tests faussés, pas d’adaptation sur l’INR. Stop 2–3 j avant un bilan d’APL."),
    Q("330", "A",
      "Coronarien en prévention secondaire, chirurgie ORL réglée. Gestion de l’aspirine : indiquer la ou les proposition(s) exacte(s).",
      [("Après un stent, retarder de 3–6 mois tout acte invasif à risque non urgent.", "Délai."),
       ("Risque hémorragique modéré (fibroscopie, stomatologie) : ne pas arrêter l’aspirine.", "Consensus."),
       ("Risque très important (ORL, urologie, neurochir) : arrêt court 5 j, reprise aussi tôt que possible.", "Durée."),
       ("Arrêter l’aspirine expose à un événement athérothrombotique (stent, IDM).", "Risque."),
       ("L’aspirine de prévention primaire reste systématique chez tout diabétique.", "Plus recommandée, même chez le diabétique.")],
      ["A", "B", "C", "D"],
      "Stent : reporter 3–6 mois. Geste modéré : on garde l’aspirine. Geste majeur : 5 j d’arrêt."),
    Q("330", "A",
      "Danaparoïde, bivalirudine, fondaparinux : indiquer la ou les proposition(s) exacte(s).",
      [("Danaparoïde (Orgaran®) : TIH (ou ATCD de TIH) nécessitant encore une ACO.", "Indication."),
       ("En TIH : danaparoïde au moins prophylactique jusqu’à correction des plaquettes.", "Conduite."),
       ("Bivalirudine : anticoagulant IV surtout lors des angioplasties.", "Place."),
       ("Fondaparinux : T½ 17–21 h, 1 inj/j, CI si ClCr < 30, pas d’antidote commercialisé dans le tableau du cours.", "Tableau 22.4."),
       ("En TIH, on double l’HNF tant que le TCA n’est pas à 4 × le témoin.", "On arrête toute héparine.")],
      ["A", "B", "C", "D"],
      "TIH : stop héparine, danaparoïde. Bivalirudine : coronaire. Fonda : 1/j, CI rénale."),
    Q("330", "B",
      "Chute de plaquettes sous HNF à J6 : score des 4T. Indiquer la ou les proposition(s) exacte(s).",
      [("4T : Thrombopénie, Timing, Thrombose, auTres causes.", "Structure."),
       ("Timing typique 5–10 j, ou dès 24 h si héparine dans les 30 j ; 0–3 faible, 4–5 intermédiaire, 6–8 élevé.", "Lecture."),
       ("Suspicion forte : arrêt héparine et alternative sans attendre l’anti-PF4.", "Urgence."),
       ("Elisa anti-PF4 : meilleure VPN que VPP.", "Bio."),
       ("Un score à 1 affirme une TIH certaine et impose un filtre cave sans NFS.", "0–3 = risque faible.")],
      ["A", "B", "C", "D"],
      "4T : intensité, délai 5–10 j, thrombose, autre cause. Ne pas attendre l’Elisa si forte suspicion."),
    Q("330", "A",
      "Calendrier de l’INR sous AVK : indiquer la ou les proposition(s) exacte(s).",
      [("2×/sem J0–J14, 1×/sem jusqu’à J30, /15 j jusqu’à J60, puis ≥ 1×/mois.", "Fig. 22.3."),
       ("Équilibré si ≥ 70 % des INR dans la cible.", "TTR."),
       ("Automesure remboursée en France seulement chez l’enfant et le porteur de valve mécanique.", "Remboursement."),
       ("Éducation : coprescriptions, seuils d’alerte, saignement, prévenir tout soignant.", "ETP."),
       ("Après J60, un INR annuel unique suffit, même sous miconazole.", "Minimum mensuel ; miconazole CI.")],
      ["A", "B", "C", "D"],
      "INR rapproché à l’initiation, puis ≥ 1/mois. TTR ≥ 70 %. Automesure enfant/valve."),
    Q("330", "A",
      "Polytraumatisé sous AVK, choc crânien. Indiquer la ou les proposition(s) exacte(s).",
      [("INR en urgence.", "1er geste."),
       ("TC : hospitalisation ≥ 24 h et TDM cérébral urgent.", "Spécifique."),
       ("Hémorragie grave : stop AVK, vit K + CCP/PPSB, sans attendre l’INR pour commencer.", "Contexte traumatique."),
       ("Après injection de CCP, un contrôle d’INR est inutile : la vitamine K suffit à elle seule en urgence.", "INR à 30 min ; si > 1,5, complément de CCP. Vit K et CCP sont associés."),
       ("Retour à domicile sans imagerie si l’examen neuro initial est normal.", "Hospit ≥ 24 h + TDM.")],
      ["A", "B", "C"],
      "TC sous AVK : INR, TDM urgent, hospit ≥ 24 h. Hémorragie grave : vit K + PPSB, contrôle à 30 min."),
    Q("330", "A",
      "Avantages/limites des AOD vs AVK (tableau 22.11), hors le choix valve/RM déjà traité. Indiquer la ou les proposition(s) exacte(s).",
      [("Action rapide, pas de surveillance d’effet, moins d’HIC, instauration simple.", "Avantages."),
       ("Accumulation si IR, observance difficile à vérifier, un peu plus d’hémorragies digestives et génitales.", "Inconvénients."),
       ("Élimination rénale : dabigatran 80 %, rivaroxaban 33 %, apixaban 25 %.", "Pourcentages."),
       ("Demi-vie courte : le temps depuis la dernière prise est un levier majeur en cas de saignement.", "Gestion."),
       ("Le dabigatran est l’AOD de choix si ClCr 15 mL/min, car il n’a pas d’élimination rénale.", "C’est l’inverse : 80 % rénaux, CI si ClCr < 25–30.")],
      ["A", "B", "C", "D"],
      "AOD : moins d’HIC, plus de saignements digestifs, accumulation rénale (dabigatran +++). Pas de dabigatran en IR sévère."),
    Q("330", "A",
      "Syndrome de Widal et effets de l’aspirine : indiquer la ou les proposition(s) exacte(s).",
      [("Inhibition COX-1 irréversible 7–10 j, baisse du thromboxane A2.", "Mécanisme."),
       ("Effets AINS/antipyrétiques à des doses > 1 g/j, très supérieures à la dose antiplaquettaire.", "Dissociation."),
       ("EI : saignements et intolérance gastrique ; allergies rares.", "Tolérance."),
       ("Widal : asthme + polypose nasale + allergie à l’aspirine.", "Triade."),
       ("Un test d’agrégation mensuel est obligatoire pour titrer 75 mg.", "Pas de test fiable de routine.")],
      ["A", "B", "C", "D"],
      "Aspirine : COX irréversible 7–10 j. Widal = asthme + polypose + allergie. Pas de monitoring d’agrégation."),
    Q("330", "A",
      "Homme de 82 ans, INR cible 2,5, INR à 7 sans saignement. Tableau HAS : indiquer la ou les proposition(s) exacte(s).",
      [("6 < INR < 10 : arrêt, vit K 1–2 mg PO, adaptation à la reprise, contrôle le lendemain.", "Ligne 6–10."),
       ("INR < 4 : pas de saut de prise, pas de vit K, simple adaptation.", "Ligne < 4."),
       ("4 < INR < 6 : saut d’une prise, pas de vit K.", "Ligne 4–6."),
       ("INR > 10 : arrêt + vit K 5 mg PO.", "Ligne > 10."),
       ("INR 7 asymptomatique = 30 UI/kg de PPSB et intubation, comme une hémorragie grave.", "Surdosage asymptomatique = vit K PO, souvent ambulatoire.")],
      ["A", "B", "C", "D"],
      "Cible 2,5 sans saignement : <4 adapter ; 4–6 sauter une prise ; 6–10 vit K 1–2 mg ; >10 vit K 5 mg. PPSB = hémorragie grave."),
]

from collections import Counter
c = Counter(q["item"] for q in questions)
print("COUNTS", dict(c), "TOTAL", len(questions))
assert c["234"] >= 22 and c["203"] >= 12 and c["226"] >= 20
assert c["235"] >= 12 and c["331"] >= 14 and c["330"] >= 16
assert len(questions) >= 96

vignettes = sum(1 for q in questions if any(x in q["prompt"] for x in (
    "Homme", "Femme", "femme", "homme", "ans,", "ans ", "Sportif", "Asthmatique",
    "Jambe", "Cancer", "SCA ", "Patient", "Polytraumatisé", "Un patient", "Un BPCO",
    "Au domicile", "0 h 30", "ROSC", "Témoin", "TVP distale", "EP confirmée",
    "Coronarien",
)))
print("approx vignettes", vignettes)

for q in questions:
    n = len(q["correct"])
    assert 2 <= n <= 4, q["prompt"][:80]
    assert len(q["options"]) == 5
    assert all("why" in o and o["why"] for o in q["options"])

OUT.write_text(json.dumps({"questions": questions}, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
print("written", OUT, "bytes", OUT.stat().st_size)
