# -*- coding: utf-8 -*-
"""Fill reflexes / pieges / seuils into fiches.json."""
from __future__ import annotations

import json
from pathlib import Path

OUT = Path(__file__).with_name("fiches.json")

REFLEXES = [
    {
        "item": "230",
        "label": "230 Douleur thoracique",
        "keywords": ["PIED", "15", "ECG avant Tn", "18 dérivations"],
        "redFlags": [
            "Détresse : FR > 30 ou < 10, SpO2 < 90 %, choc, pouls paradoxal, trouble de conscience",
            "4 urgences PIED (péricardite, infarctus, EP, dissection) + rupture œsophage",
            "Ne pas appeler le 15 = faute grave (mortalité préhospitalière du SCA)",
        ],
        "bilan": [
            "ECG 12 dér. + V3R V4R V7–V9 immédiat — avant la troponine",
            "Radio pulmonaire, Tn-us",
            "Echo/TDM en urgence si EP ou dissection suspectée",
        ],
        "arbre": {
            "premiere": [
                "Détresse → réa. ST+ persistant → USIC / salle de coro médicalisé",
                "Sinon tri PIED. Angor chronique : score de proba (aucun examen si < 5 %)",
            ],
            "echec": ["ECG percritique normal n’élimine pas un SCA — renouveler à 1–2 h ou si récidive"],
            "terrains": ["Pacemaker : ECG peu lisible → coro si angor prolongé", "Femme, âgé, diabète : douleurs atypiques, même CAT"],
        },
        "ciei": ["TNT peut calmer un spasme œsophagien — n’élimine pas les urgences", "Tn initiale négative n’élimine pas un angor instable"],
        "rangA": ["CAT, 4 urgences, sémiologie dissection, ECG/radio/bio"],
        "rangB": ["Place de la coro dans le SCA", "Echo/ETO/TDM de dissection"],
    },
    {
        "item": "339",
        "label": "339 SCA / angor",
        "keywords": ["PCI 120 min", "DAPT 12 / 6 mois", "SaO2 90 %", "BASIC"],
        "redFlags": [
            "ECG < 10 min. ST+ = reperfusion urgente",
            "ST− très haut risque : choc, douleur persistante, IC, TV/FV, variation ECG dynamique → coro < 2 h",
            "Souffle systolique (CIV, rupture de pilier). Triade IDM VD : ST+ inf. + hypotension + poumons clairs",
        ],
        "bilan": ["ECG 18 dér.", "Tn-us (ST−, algorithme H0 ± 1–2 h)", "Glycémie, lipides, créat, NFS", "ETT (ST− ; ST+ si mécanique)"],
        "arbre": {
            "premiere": [
                "ST+ : PCI si ≤ 120 min sinon fibrinolyse + transfert. Aspirine 250 mg IV puis 75–100 + prasugrel ou ticagrélor",
                "ST− : aspirine + anticoag ; pas de P2Y12 avant coro (sauf délai > 24 h)",
                "Angor stable : aspirine + statine LDL < 0,55 + TNT de crise + BB",
            ],
            "echec": [
                "Lyse si PCI > 120 min, sauf CI (AVC hémorragique, AVC < 6 mois, dissection, HDB < 1 mois…)",
                "Clopidogrel si CI prasugrel/ticagrélor. Lyse = clopidogrel seul (charge 300 mg si < 75 ans)",
            ],
            "terrains": [
                "Prasugrel : CI si ATCD d’AVC ; éviter ≥ 75 ans et/ou < 60 kg",
                "IDM VD : CI vasodilatateurs. ACO nécessaire : bithérapie clopidogrel + ACO 12 mois",
                "Pontage : TCG, tritronculaire complexe, surtout diabétique",
            ],
        },
        "ciei": [
            "Nitrés CI avec iPDE5. O2 seulement si SaO2 < 90 % ou PaO2 < 60 (hyperoxie délétère)",
            "BB : CI asthme, BAV 2–3, FC < 50. Ne pas associer ICa bradycardisant + BB",
        ],
        "rangA": ["Définitions, ECG, Tn, 15, stratégies ST+/ST−/stable, DAPT"],
        "rangB": ["Physio thrombus blanc/rouge", "Choix PCI vs pontage", "MINOCA"],
    },
    {
        "item": "235",
        "label": "235 Péricardite",
        "keywords": ["2/4 critères", "colchicine 3 mois", "tamponnade", "pas de CTC 1re ligne"],
        "redFlags": [
            "Tamponnade : PAS < 90, pouls paradoxal (10 mmHg), bruits assourdis, jugulaires — drainage",
            "Hospit. si fièvre > 38 °C, début subaigu, épanchement > 20 mm, résistance AINS ≥ 7 j",
        ],
        "bilan": ["ECG + echo systématiques", "NFS, CRP, Tn, iono, créat", "Hémocultures si fièvre"],
        "arbre": {
            "premiere": [
                "AINS 1–2 sem (aspirine 750–1000 mg/8 h ou ibuprofène 600 mg/8 h) + IPP",
                "Colchicine 0,5 mg × 2/j × 3 mois (0,5 mg/j si < 70 kg, > 70 ans, DFG < 35)",
                "Repos sport jusqu’à clinique + CRP + ECG + echo normales",
            ],
            "echec": ["Corticoïdes pas en 1re intention. Si échec : 0,25–0,5 mg/kg/j AVEC la bithérapie"],
            "terrains": ["CI colchicine : IRC sévère", "Post-IDM précoce J3–J5 ≠ Dressler 2e–16e semaine"],
        },
        "ciei": ["Interactions colchicine : macrolides, ciclosporine, vérapamil, statines", "CTC d’emblée = inacceptable"],
        "rangA": ["2 critères/4, ECG 4 stades, tamponnade, schéma AINS+colchicine"],
        "rangB": ["Étiologies rares, corticoïdes, scanner/IRM 2e intention"],
    },
    {
        "item": "234",
        "label": "234 Insuffisance cardiaque",
        "keywords": ["4 piliers", "FEVG < 40", "PAS 100/110", "CRT/DAI"],
        "redFlags": ["OAP", "Choc : PAS < 90 ou −30 mmHg ≥ 30 min, oligurie < 20 mL/h", "QRS ≥ 130 ms + FEVG ≤ 35 %"],
        "bilan": ["ECG, Rx, iono/créat, BNP/NT-proBNP, NFS, ferritine+CST, TSH, ETT"],
        "arbre": {
            "premiere": [
                "HFrEF : IEC/ARNI + BB (4 molécules) + ARM + gliflozine ± diurétique d’anse",
                "OAP : assis, furosémide 1 mg/kg IV, nitrés SL si PAS > 100 / IV si PAS > 110, O2 si SaO2 < 90 %",
            ],
            "echec": ["Ivabradine si RS et FC > 70–75 malgré BB", "CRT si QRS ≥ 130 ms ; DAI si FEVG < 35 % NYHA II–III et survie > 1 an"],
            "terrains": ["HFpEF : gliflozine + FDR", "Ne pas introduire un BB en poussée d’OAP", "Amiodarone = seul AA si FEVG basse"],
        },
        "ciei": ["CI HFrEF : diltiazem/vérapamil, flécaïnide, AINS", "IEC : stop si créat ↑ > 20–30 %, CI grossesse/angio-œdème/sténose rénale bilatérale"],
        "rangA": ["Définitions FEVG, OAP, choc, 4 piliers, ttt OAP, DAI"],
        "rangB": ["Détails CRT, HFpEF ABCDEFG, greffe"],
    },
    {
        "item": "203",
        "label": "203 Dyspnée",
        "keywords": ["SpO2 90 %", "pseudoasthme cardiaque", "BNP"],
        "redFlags": ["Tirage, SpO2 < 90 %, FC > 120, choc, cyanose, encéphalopathie"],
        "bilan": ["Clinique, Rx, ECG, NFS, D-dimères, BNP/NT-proBNP, GDS"],
        "arbre": {
            "premiere": ["O2 si SpO2 < 90 %", "OAP : diurétique ± TNT IV (la réponse aide le diagnostic)"],
            "echec": ["SDRA / tamponnade / EP : orientation spécifique, pas un BB IV systématique"],
            "terrains": ["Pseudoasthme cardiaque = équivalent d’OAP", "Tamponnade : choc droit, poumons clairs, pas de diurétiques d’OAP"],
        },
        "ciei": ["Ne pas oxygéner trop tard en attendant la radio"],
        "rangA": ["Gravité, O2, orientation OAP/EP/tamponnade"],
        "rangB": ["Étiologies rares"],
    },
    {
        "item": "232",
        "label": "232 Fibrillation atriale",
        "keywords": ["CHA2DS2-VA", "pas de sexe", "AOD", "3 sem / 4 sem"],
        "redFlags": ["Choc → CEE immédiat", "OAP, embolie"],
        "bilan": ["Iono, créat, TSH, NFS, ETT, Rx. Holter 72 h si FA non documentée (AVC)"],
        "arbre": {
            "premiere": [
                "CHA2DS2-VA 0–8 (sans point sexe) : 0 pas d’ACO, = 1 discussion, > 1 ACO. AOD préférés",
                "Freinateurs : BB, diltiazem/vérapamil, digoxine (FC < 110 à la marche)",
            ],
            "echec": ["Ablation des VP = 1re ligne possible en FA paroxystique", "Cardioversion : ACO ≥ 3 sem avant + ≥ 4 sem après (sauf ETO N ou FA < 24 h)"],
            "terrains": ["Mécanique ou RM modéré–sévère : AVK, score non applicable", "Coronaire ou IC : amiodarone seule comme AA", "CMH / amylose : ACO systématique"],
        },
        "ciei": ["ICa bradycardisants interdits si IC à FE basse", "1er épisode : pas d’AA chronique de principe"],
        "rangA": ["ECG, CHA2DS2-VA, bilan, contrôle FC/rythme, cardioversion"],
        "rangB": ["Ablation, fermeture d’auricule si score > 2 + CI ACO permanente"],
    },
    {
        "item": "236",
        "label": "236 Conduction",
        "keywords": ["BAV 3", "Mobitz 2", "isoprénaline CI IDM", "VVI si FA"],
        "redFlags": ["BAV 3, Mobitz 2, haut degré, BB alternant, BSA 3, syncope + ECG conductif"],
        "bilan": ["ECG 12 dér. ± tracé long. Iono, TSH. ETT si cardiopathie"],
        "arbre": {
            "premiere": ["Urgence : atropine (nodal/sinusal), isoprénaline hors IDM, puis stimulation temporaire", "PM définitif : BAV 3, Mobitz 2, haut degré, DS symptomatique liée"],
            "echec": ["Pauses sinusales > 3 s sympto ou > 6 s même asympto"],
            "terrains": ["IDM : isoprénaline CI. BAV inf. souvent régressif (discuter PM à J5)", "FA permanente + BAV → VVI (pas DDD). BAV + FEVG < 50 % → CRT ou stim branche G"],
        },
        "ciei": ["Atropine peut aggraver un BAV infrahissien", "BBG n’est jamais « bénin » ; BBD isolé jeune souvent variante"],
        "rangA": ["ECG, urgence, indications de PM"],
        "rangB": ["Étiologies, BAV congénital anti-Ro/SSA"],
    },
    {
        "item": "237",
        "label": "237 Palpitations",
        "keywords": ["adénosine", "WPW", "QRS larges = TV"],
        "redFlags": ["FC > 150, hypoTA, angor, IC, syncope, QRS larges"],
        "bilan": ["ECG. Iono, NFS, β-hCG, TSH. ETT (Rang B, souvent systématique)"],
        "arbre": {
            "premiere": ["Bouveret : vagales + adénosine flash. Ablation voie lente si récidives", "QRS larges réguliers : TV jusqu’à preuve du contraire"],
            "echec": ["Pill-in-the-pocket si peu de crises de TRIN"],
            "terrains": ["WPW malin (PRE < 250 ms) : ablation. FA + Kent : CEE si instable ; jamais adénosine/BB/ICa/digoxine"],
        },
        "ciei": ["Adénosine CI asthme et HTA non contrôlée"],
        "rangA": ["Sémiologie, ECG, CAT crise, CI WPW"],
        "rangB": ["Holter implantable, détails d’ablation"],
    },
    {
        "item": "342",
        "label": "342 Syncope / PDCB",
        "keywords": ["effort/couché", "pauses 3 s", "HO 20/10"],
        "redFlags": ["ATCD familiaux MS jeune, FE basse, effort/couché/palpitations, souffle éjectionnel, ECG patho, traumatisme grave"],
        "bilan": ["Interrogatoire + clinique + ECG (résout > 50 %). ETT quasi systématique"],
        "arbre": {
            "premiere": ["Réflexe : éducation, sel/eau, isométriques, baisser hypotenseurs", "HO : stop hypotenseurs"],
            "echec": ["PM rare si bradycardie/asystolie documentée prédominante", "Fludrocortisone / α-agonistes : 2e recours"],
            "terrains": ["Massage sinus carotidien si > 40 ans (CI AIT/AVC/sténose carotide)"],
        },
        "ciei": ["Ne pas appeler « syncope convulsivante »", "Perte d’urines et somnolence peu discriminants vs épilepsie"],
        "rangA": ["Classification, ECG diagnostic immédiat, CAT réflexe"],
        "rangB": ["Tilt test, indications PM"],
    },
    {
        "item": "226",
        "label": "226 TVP / EP",
        "keywords": ["Wells/Genève", "D-dimères", "3 mois", "AOD"],
        "redFlags": ["EP haut risque : choc / PAS < 90", "TVP avec signes d’EP"],
        "bilan": ["Score de proba d’abord. D-dimères seulement si proba faible/intermédiaire. Angio-TDM si EP. Echo-Doppler si TVP"],
        "arbre": {
            "premiere": ["Non grave : AOD (riva 15×2/21 j puis 20 ; apixa 10×2/7 j puis 5×2) ou HBPM", "Haut risque : fibrinolyse + HNF en USIC"],
            "echec": ["Embolectomie si CI à la lyse", "HNF si DFG < 30"],
            "terrains": ["Cancer / SAPL / récidive : ACO non limitée. COP et THM CI après MTEV", "TVP distale 1er épisode provoquée : 6 semaines possibles"],
        },
        "ciei": ["Aspirine n’est pas une prévention de MTEV", "Contention classe 3, CI si IPS < 0,6"],
        "rangA": ["Définitions, scores, D-dimères, ttt initial, prévention"],
        "rangB": ["Durées ACO, cancer occulte, SPT, HTP-TEC"],
    },
    {
        "item": "233RA",
        "label": "233 RA",
        "keywords": ["Vmax 4", "surface 1 cm²", "TAVI 75 ans", "syncope d’effort"],
        "redFlags": ["RA serré sympto (dyspnée, angor, syncope d’effort)", "Bas débit / FEVG basse (pseudosténose vs bas flux)"],
        "bilan": ["ETT. Coronaro préop si H > 40 ans, F ménopausée, FDR, angor, IC"],
        "arbre": {
            "premiere": ["Remplacement si serré sympto. TAVI 1re intention > 75 ans si voie fémorale", "Heart Team"],
            "echec": ["Valvuloplastie au ballon quasi abandonnée (pont vers chir non cardiaque urgente)"],
            "terrains": ["Mécanique si jeune (AVK à vie). Bioprotèse si > 65 ans"],
        },
        "ciei": ["Ne pas attribuer un « simple malaise » à l’âge devant un RA serré"],
        "rangA": ["Sémiologie, critères de sévérité, indications de remplacement/TAVI"],
        "rangB": ["Score calcique discordant (> 2000 H / > 1200 F), dobutamine si bas débit"],
    },
    {
        "item": "233IM",
        "label": "233 IM",
        "keywords": ["FEVG 60 %", "SOR 40 / 30", "plastie"],
        "redFlags": ["IM aiguë + OAP/choc → chir urgente", "FEVG < 60 % = déjà une dysfonction"],
        "bilan": ["ETT (SOR, VR, PAPS, AG). ETO si mécanisme"],
        "arbre": {
            "premiere": ["Primaire importante : chirurgie, réparation de préférence", "Secondaire : optimiser IC (médicaments, CRT) avant le geste"],
            "echec": ["Clip si haut risque / CI chir", "ACO si FA"],
            "terrains": ["Remplacement mitral CI si FE < 30 % (plastie encore possible)"],
        },
        "ciei": ["Pas d’antibioprophylaxie EI de routine sur valve native (hygiène dentaire)"],
        "rangA": ["Primaire vs secondaire, indications opératoires, médical de l’aiguë"],
        "rangB": ["Seuils SOR secondaire 30 mm², clip"],
    },
    {
        "item": "233IA",
        "label": "233 IA",
        "keywords": ["BB CI", "IEC non reco", "Marfan 50 mm"],
        "redFlags": ["IA aiguë (EI, dissection) mal tolérée", "DTS > 50 mm ou FEVG ≤ 50 %"],
        "bilan": ["ETT + mesure de la racine aortique"],
        "arbre": {
            "premiere": ["Chir si sévère sympto ou dysfonction VG. Pas de ttt médical du remodelage"],
            "echec": ["TAVI n’est pas un traitement de l’IA (exception très haut risque sans EI)"],
            "terrains": ["Marfan : BB validés pour l’aorte ; chir racine ≥ 50 mm (45 mm si FDR)"],
        },
        "ciei": ["IEC non recommandés pour prévenir le remodelage", "BB CI (allongent la diastole) sauf Marfan / aorte dilatée"],
        "rangA": ["Sémiologie, indications chir, CI BB/IEC"],
        "rangB": ["Seuils aorte selon Marfan/bicuspidie"],
    },
    {
        "item": "152",
        "label": "152 Endocardite",
        "keywords": ["3 hémocultures", "haut risque", "Duke", "chirurgie 50 %"],
        "redFlags": ["Fièvre + cardiopathie à risque / souffle nouveau / embolie / purpura / lombalgie", "IC, choc, abcès, végétation > 10 mm après embolie"],
        "bilan": ["3 hémocultures ≥ 30 min AVANT toute ATB", "ETT puis ETO si ETT+ ou suspicion forte ou matériel"],
        "arbre": {
            "premiere": ["ATB bactéricide, IV, synergique, 4–6 sem", "Probabiliste seulement si sepsis / chir urgente, après hémocultures"],
            "echec": ["Chir ~50 % en phase active : 24 h si choc ; 3–5 j si IC/abcès/végétations"],
            "terrains": [
                "Prophylaxie seulement haut risque (prothèse y compris TAVI, ATCD EI, cyanogène non corrigée) avant geste dentaire gingival/périapical",
                "Amox 2 g PO 30–60 min avant (152). Le 153 écrit 3 g — les deux chiffres sont dans le collège",
            ],
        },
        "ciei": ["Pas de prophylaxie pour coloscopie ni pour IM/prolapsus isolé", "S. gallolyticus → coloscopie"],
        "rangA": ["Évoquer, hémocultures, ETT/ETO, ATB de principe, qui est à haut risque"],
        "rangB": ["Schémas selon germe, indications chir détaillées"],
    },
    {
        "item": "153",
        "label": "153 Prothèses",
        "keywords": ["AOD CI", "INR", "fièvre = hémocultures"],
        "redFlags": ["Fièvre, souffle nouveau, bruits diminués, accident embolique, dyspnée brutale"],
        "bilan": ["Hémocultures avant ATB. ETT/ETO. INR"],
        "arbre": {
            "premiere": ["Mécanique : AVK à vie, jamais d’AOD", "Bioprotèse : pas d’ACO de principe au long cours"],
            "echec": ["Thrombose obstructive : urgence — chir ou fibrinolyse selon tableau. HNF + aspirine en Usic"],
            "terrains": ["Grossesse mécanique : AVK tératogènes S6–S12 surtout si warfarine > 5 mg"],
        },
        "ciei": ["Fluindione = 2e intention (néphrite immunoallergique)"],
        "rangA": ["INR, AOD CI, suivi, CAT fièvre/thrombose"],
        "rangB": ["Cibles INR selon risque prothèse × patient"],
    },
    {
        "item": "221",
        "label": "221 Athérome / polyvasculaire",
        "keywords": ["≥ 2 territoires", "aspirine + statine", "IPS"],
        "redFlags": ["Claudication, souffle, pouls abolis, ΔPA bras > 15 mmHg, dysfonction érectile"],
        "bilan": ["Clinique tous territoires, ECG systématique, IPS, échodoppler MI (B), dépistage AAA H > 65 ans"],
        "arbre": {
            "premiere": ["Aspirine (ou clopidogrel) + statine (cibles secondaire) + IEC/ARA2 + FDR", "BB seulement si indication formelle (post-IDM / FE basse)"],
            "echec": ["Sténose coronaire > 70 % post-SCA ; FFR < 0,8"],
            "terrains": ["Polyvasculaire : ≥ 2 territoires. Plaque carotidienne < 50 % ne compte pas"],
        },
        "ciei": ["Oublier aspirine ET statine en secondaire = inacceptable"],
        "rangA": ["Définition polyvasculaire, ttt médical de morbimortalité"],
        "rangB": ["IPS, seuils invasifs AAA/carotide"],
    },
    {
        "item": "222",
        "label": "222 FDR / prévention",
        "keywords": ["BASIC", "LDL 0,55", "SCORE2", "Interheart"],
        "redFlags": ["Coronarien jeune H < 55 / F < 65 → enquête familiale"],
        "bilan": ["SCORE2 en primaire (ne s’applique pas si MCV, diabète, HF, IRC)", "EAL, glycémie, PA hors cabinet"],
        "arbre": {
            "premiere": ["Secondaire : BASIC (BB, AAP, statine, IEC, contrôle FDR). Statine systématique, LDL < 0,55", "Primaire : diététique ≥ 3 mois avant médicament sauf très haut risque"],
            "echec": ["Chaque classe BASIC post-IDM ↓ mortalité totale ~ 25 %"],
            "terrains": ["Substituts nicotiniques autorisés chez le coronarien. AP ≥ 150–300 min/sem modérée"],
        },
        "ciei": ["Oublier BASIC après un IDM = inacceptable"],
        "rangA": ["FDR, SCORE2, BASIC, cibles secondaire"],
        "rangB": ["Excès de poids, détails SCORE2-OP"],
    },
    {
        "item": "223",
        "label": "223 Dyslipidémies",
        "keywords": ["statine", "ézétimibe", "PCSK9 0,7", "TG 5 / 10"],
        "redFlags": ["TG > 10 g/L → pancréatite", "HF (xanthomes, LDL 2–4 g/L hétérozygote)"],
        "bilan": ["EAL : CT, HDL, TG → Friedewald si TG < 3,5. TSH, foie, créat, glycémie"],
        "arbre": {
            "premiere": ["Statine 1re. Objectif très haut risque / secondaire : LDL < 0,55 et −50 %", "Ézétimibe si cible non atteinte"],
            "echec": ["Anti-PCSK9 si LDL > 0,7 g/L en secondaire sous ttt max", "HTG > 5 g/L : fibrate. HTG 1,5–5 : diète seule"],
            "terrains": ["Statines CI grossesse. Primaire : diète ≥ 3 mois sauf très haut risque"],
        },
        "ciei": ["Stop si CPK > 5 N ou ALAT > 3 N", "CPK non systématique si asymptomatique"],
        "rangA": ["Types, Friedewald, arbre statine/ézétimibe/PCSK9, cibles"],
        "rangB": ["HF, secondaires, fibrates"],
    },
    {
        "item": "224",
        "label": "224 HTA",
        "keywords": ["bithérapie", "jamais IEC+ARA2", "120–129 / 70–79", "crise ≠ urgence"],
        "redFlags": ["Urgence : atteinte d’organe. Maligne : FO stade 4. HO : −20/−10"],
        "bilan": ["Confirmer hors cabinet (AMT règle des 3, MAPA). Glycémie, EAL, iono, créat, PU, ECG. FO si grade 2–3"],
        "arbre": {
            "premiere": ["Bithérapie d’emblée IEC/ARA2 + IC ou thiazidique (comprimé fixe)", "Cible ESC : PAS 120–129 et PAD 70–79"],
            "echec": ["À 1 mois : trithérapie + thiazidique. Résistante : + spironolactone"],
            "terrains": ["Mono si fragilité, HO, > 85 ans. Urgence : urapidil/nicardipine IV (nicardipine CI si IC)"],
        },
        "ciei": ["Jamais IEC + ARA2. IEC : grossesse, angio-œdème. BB : asthme, BAV 2–3. Thiazidiques : goutte"],
        "rangA": ["Mesure, grades, bithérapie, CI, crise vs urgence"],
        "rangB": ["Secondaires, phéo = labétalol IV"],
    },
    {
        "item": "225",
        "label": "225 AOMI / anévrismes",
        "keywords": ["IPS 0,90", "50–55 mm", "marche supervisée"],
        "redFlags": ["Claudication < 100 m, douleur de décubitus, pied froid, masse battante, douleur abdo + choc"],
        "bilan": ["IPS. Échodoppler 1re. Angio seulement si revasc. Écho AAA H > 65 ans"],
        "arbre": {
            "premiere": ["AAP si symptomatique + statine LDL < 0,55 −50 % + IEC + marche 30–45 min × 3/sem", "Ischémie permanente : revasc autant que possible"],
            "echec": ["Prostaglandines IV si non revascularisable. Amputation en zone viable (TcPO2)"],
            "terrains": ["BB possibles si indication formelle, prudence si critique non revascularisable", "DAPT 1–6 mois après angioplastie"],
        },
        "ciei": ["Pentoxifylline : périmètre seulement, pas de pronostic", "AAP débattu si AOMI isolée asymptomatique"],
        "rangA": ["IPS, ttt général, ischémie critique, AAA 50–55 mm"],
        "rangB": ["Techniques de revasc, anévrisme poplité > 20 mm"],
    },
    {
        "item": "330",
        "label": "330 Antithrombotiques",
        "keywords": ["TIH", "protamine", "idarucizumab", "INR"],
        "redFlags": ["Saignement, TCA > 3×, plaquettes < 100 ou −30–50 % sous héparine, thrombose sous héparine"],
        "bilan": ["INR (AVK), TCA/anti-Xa (HNF), plaquettes si TIH à risque"],
        "arbre": {
            "premiere": ["HNF si IR / instable. HBPM/fonda si DFG OK. AOD si FA non valvulaire / MTEV", "AVK si mécanique / RM"],
            "echec": ["Hémorragie AVK grave : PPSB + vit K sans attendre l’INR", "TIH : stop toute héparine, danaparoïde"],
            "terrains": ["Dabigatran : idarucizumab. Aspirine : si arrêt pour geste, 5 j max en prévention secondaire"],
        },
        "ciei": ["HBPM/AOD si IR sévère. AOD si mécanique ou RM. TIH = risque thrombotique, pas hémorragique"],
        "rangA": ["Classes, surveillance, antidotes, TIH, CI AOD"],
        "rangB": ["4T, posologies détaillées, fibrinolyse"],
    },
    {
        "item": "331",
        "label": "331 Arrêt cardiaque",
        "keywords": ["ACD", "MCE 100/min", "pas de bouche-à-bouche", "amiodarone 300"],
        "redFlags": ["Inconscient + ventilation nulle/anormale (gasps). Appeler 15"],
        "bilan": ["Rythme au DSA : chocable vs non chocable"],
        "arbre": {
            "premiere": ["MCE immédiat 4–5 cm ~ 100/min + DEA. Dégagement VAS, pas de bouche-à-bouche adulte", "FV/TV : CEE. Amiodarone 300 mg avant le 3e choc"],
            "echec": ["Adrénaline 1 mg / 4 min. Lidocaïne seulement si pas d’amiodarone", "Post-ROSC : dobutamine si sidération ; coro si SCA suspecté"],
            "terrains": ["Enfant/nourrisson : insufflations utiles (cause souvent hypoxique)"],
        },
        "ciei": ["Thrombolyse préhospitalière non systématique", "Intubation : pause MCE < 30 s"],
        "rangA": ["Diagnostic, ACD, MCE, DSA, rythmes chocables"],
        "rangB": ["Médicaments ALS, post-ROSC"],
    },
    {
        "item": "238",
        "label": "238 Souffle enfant",
        "keywords": ["jamais diastolique innocent", "pouls fémoraux", "CIV 1re année"],
        "redFlags": ["Cyanose, IC, pouls fémoraux abolis, thrill, B2 fixe, souffle néonatal"],
        "bilan": ["Souffle néonatal : ETT avant sortie de maternité. Innocent : aucun examen"],
        "arbre": {
            "premiere": ["Innocent : réassurance, sport autorisé", "Coarctation néonatale : chir urgente", "Large CIV : opérer dans la 1re année"],
            "echec": ["Prophylaxie EI seulement si haut risque (152), pas pour tout souffle"],
            "terrains": ["TGV : cyanose sans souffle. Fallot : chir 6 mois–1 an"],
        },
        "ciei": ["Intensité du souffle ≠ gravité"],
        "rangA": ["Innocent vs organique, coarctation, shunts G-D"],
        "rangB": ["Détails malfo rares"],
    },
    {
        "item": "231",
        "label": "231 ECG",
        "keywords": ["PR 120–200", "QRS 70–110", "QTc 450", "FA = irrégulier fins"],
        "redFlags": ["Sus-ST, BAV 3, TdP, TV, pauses > 3 s, WPW + FA"],
        "bilan": ["Vitesse 25 mm/s (1 mm = 40 ms). 12 dérivations ± droits/postérieurs si SCA"],
        "arbre": {
            "premiere": ["Lire : rythme, FC, axe, P, PR, QRS, ST-T, QT", "FA = seule tachycardie complètement irrégulière à QRS fins"],
            "echec": ["QRS larges réguliers = TV jusqu’à preuve du contraire"],
            "terrains": ["WPW : PR < 120 + delta. Pacemaker de réserve jonctionnel 40–60, ventriculaire 15–30"],
        },
        "ciei": ["HVG droite : T− V1–V3, ne pas appeler « ischémie » trop vite", "Dissociation VA de TV ≠ dissociation du BAV complet"],
        "rangA": ["Normales, FA/flutter, SCA, blocs, HV"],
        "rangB": ["Critères fins d’hypertrophie, variantes"],
    },
]

PIEGES = [
    {"item": "232", "rang": "A", "piege": "Utiliser le CHA2DS2-VASc (point « femme ») comme dans les éditions précédentes.", "reflexe": "CNEC 3e = CHA2DS2-VA, sans sexe, 0–8. 0 = pas d’ACO ; > 1 = ACO."},
    {"item": "232", "rang": "A", "piege": "Calculer le CHA2DS2-VA pour une prothèse mécanique ou un RM modéré–sévère, ou pour décider l’ACO autour d’une cardioversion.", "reflexe": "AVK d’emblée si mécanique/RM. Autour d’une CV : ACO obligatoire (3 sem avant / 4 sem après), le score ne s’applique pas."},
    {"item": "232", "rang": "A", "piege": "Confondre FA à grosses mailles et flutter ; confondre contrôle de fréquence et de rythme.", "reflexe": "Flutter = activité F régulière (souvent 150/min). 1er épisode : pas d’AA chronique de principe."},
    {"item": "339", "rang": "A", "piege": "Mettre une DAPT 12 mois après un stent d’angor stable, ou 6 mois après un SCA.", "reflexe": "SCA : DAPT 12 mois. Angor stable stenté : DAPT 6 mois (clopidogrel). P2Y12 « nouveaux » non indiqués dans l’angor stable."},
    {"item": "339", "rang": "A", "piege": "Oxygéner tout SCA au masque 15 L, ou précharger le ticagrélor/prasugrel dans un ST− avant la coro.", "reflexe": "O2 seulement si SaO2 < 90 % (PaO2 < 60). Pas de P2Y12 avant coro en ST− (sauf délai > 24 h)."},
    {"item": "339", "rang": "A", "piege": "Appeler STEMI un sus-ST qui cède sous TNT.", "reflexe": "Sus-ST régressif (TNT/spontané) = SCA ST− / spasme, pas une angioplastie primaire de STEMI."},
    {"item": "339", "rang": "A", "piege": "Prasugrel chez un patient avec ATCD d’AVC, ou âgé de 80 ans et 52 kg.", "reflexe": "CI si ATCD d’AVC. Éviter ≥ 75 ans et/ou < 60 kg. Clopidogrel alors."},
    {"item": "230", "rang": "A", "piege": "Doser la troponine avant l’ECG, ou se rassurer sur un ECG percritique normal.", "reflexe": "ECG immédiat (18 dér.). ECG N n’élimine ni SCA ni angor instable."},
    {"item": "230", "rang": "A", "piege": "Attendre le scanner pour anticoaguler une EP à proba haute.", "reflexe": "Proba intermédiaire ou haute : antithrombotique avant confirmation (sauf hémorragie majeure). D-dimères inutiles si proba forte."},
    {"item": "235", "rang": "A", "piege": "Corticoïdes d’emblée ; ou prendre une péricardite pour un STEMI (ST diffus).", "reflexe": "AINS + colchicine 3 mois. ST concave diffus sans miroir ni Q, sous-PQ, TNT-résistant."},
    {"item": "234", "rang": "A", "piege": "Nitrés d’OAP si PAS 85 ; ou BB d’emblée en poussée.", "reflexe": "Nitrés SL si PAS > 100 (domicile), IV si PAS > 110 (hôpital). Pas de BB en OAP non contrôlé. Pas de nitrés si choc."},
    {"item": "234", "rang": "A", "piege": "DAI chez un NYHA IV « terminal » sans projet de greffe, ou CRT sur QRS fin.", "reflexe": "DAI si survie > 1 an, NYHA II–III, FEVG < 35 %. CRT si QRS ≥ 130 ms (mieux BBG ≥ 150)."},
    {"item": "234", "rang": "A", "piege": "Diltiazem ou flécaïnide dans une HFrEF.", "reflexe": "CI. Amiodarone = seul AA si FEVG basse. 4 piliers : IEC/ARNI, BB, ARM, gliflozine."},
    {"item": "233IA", "rang": "A", "piege": "Mettre un IEC « pour le remodelage » ou un BB « comme dans l’IC » dans une IA sévère.", "reflexe": "IEC non reco pour le remodelage. BB CI (allongent la diastole) sauf Marfan / aorte dilatée."},
    {"item": "233IM", "rang": "A", "piege": "Se rassurer sur une FEVG à 55 % dans une IM primitive importante.", "reflexe": "FE surestimée par la fuite : dysfonction dès FEVG < 60 %. Secondaire : ttt IC d’abord (fuite « accordéon »)."},
    {"item": "233RA", "rang": "A", "piege": "Conclure à un RA non serré parce que le gradient moyen est < 40 mmHg.", "reflexe": "Bas débit (VES < 35 mL/m²) : surface peut rester < 1 cm². Dobutamine : si surface passe > 1 cm² = pseudosténose."},
    {"item": "153", "rang": "A", "piege": "Relayer une mécanique par un AOD « le temps que l’INR s’équilibre ».", "reflexe": "AOD CI formelle, même transitoire. Relais = HNF/HBPM. INR 2–3 sauf mitrale mécanique/disque : 3–4,5."},
    {"item": "152", "rang": "A", "piege": "Antibioprophylaxie EI pour toute valve native / toute coloscopie / tout souffle.", "reflexe": "Haut risque seulement (prothèse, ATCD EI, cyanogène) + geste dentaire gingival/périapical. Hémocultures avant ATB."},
    {"item": "226", "rang": "A", "piege": "Doser les D-dimères si proba d’EP forte ; ou traiter 12 mois toute TVP distale provoquée.", "reflexe": "Proba forte → imagerie d’emblée. Facteur transitoire majeur : 3 mois. Distale 1er épisode provoquée : 6 semaines possibles."},
    {"item": "226", "rang": "A", "piege": "Aspirine en prévention de MTEV ; ou COP après une EP.", "reflexe": "Aspirine n’est pas une prévention de MTEV. COP et THM CI après MTEV."},
    {"item": "224", "rang": "A", "piege": "Traiter une crise hypertensive (grade 3 sans organe) comme une urgence IV.", "reflexe": "Crise ≠ urgence. Urgence = atteinte d’organe. Maligne = FO stade 4. Jamais IEC + ARA2."},
    {"item": "224", "rang": "A", "piege": "Bithérapie IEC + ARA2, ou BB en monothérapie d’HTA essentielle.", "reflexe": "IEC ou ARA2 + IC ou thiazidique. BB seulement si IC, SCA, angor…"},
    {"item": "223", "rang": "A", "piege": "Cible LDL < 1,3 g/L en secondaire ; ou statine chez une femme enceinte.", "reflexe": "Secondaire / très haut risque : < 0,55 g/L et −50 %. Statines CI grossesse. PCSK9 si LDL > 0,7 sous max."},
    {"item": "222", "rang": "A", "piege": "Oublier le BASIC après un IDM, ou mettre un BB à tout polyvasculaire sans IDM.", "reflexe": "BASIC post-IDM. BB : preuve surtout post-IDM / FE basse, pas AOMI isolée."},
    {"item": "225", "rang": "A", "piege": "Opérer un AAA de 42 mm « pour ne pas rater la rupture », ou rassurer un 58 mm.", "reflexe": "Surveillance (écho / 6 mois si > 45 mm). Intervention à froid au-delà de 50–55 mm (221 : 55 mm, 50 mm femme)."},
    {"item": "225", "rang": "A", "piege": "Antiagrégant obligatoire dans toute AOMI, y compris IPS 0,85 asymptomatique isolé.", "reflexe": "AAP si symptomatique. Asx isolée : débattu, sauf autre territoire athéromateux."},
    {"item": "237", "rang": "A", "piege": "Adénosine, diltiazem ou digoxine dans une FA à QRS larges sur WPW.", "reflexe": "CI formelle (freinent le NAV, pas la voie). CEE si instable ; Ic ou amiodarone si stable."},
    {"item": "237", "rang": "A", "piege": "Traiter une tachycardie régulière à QRS larges comme un Bouveret.", "reflexe": "TV jusqu’à preuve du contraire."},
    {"item": "236", "rang": "A", "piege": "Isoprénaline dans un BAV d’IDM ; ou pacemaker DDD pour une FA permanente lente.", "reflexe": "Isoprénaline CI dans l’IDM aigu. FA + BAV → VVI."},
    {"item": "236", "rang": "A", "piege": "Pacemaker pour un BAV 1er à PR 220 ms asymptomatique, ou une dysfonction sinusale asymptomatique.", "reflexe": "DS : symptômes liés (ou pauses > 6 s). BAV 1er : discussion seulement si PR > 300 ms."},
    {"item": "342", "rang": "A", "piege": "Appeler syncope une IC stade IV, ou épilepsie des myoclonies brèves après la chute.", "reflexe": "IC IV n’est jamais une syncope. Myoclonies < 10, après la PDCB, asynchrones ; morsure du bout de la langue."},
    {"item": "342", "rang": "A", "piege": "Diagnostiquer une vasovagale chez un coronarien FE 30 % sans avoir éliminé le cardiaque.", "reflexe": "Vasovagale sur cardiopathie = diagnostic d’élimination. Hospitaliser si FDR."},
    {"item": "331", "rang": "A", "piege": "Bouche-à-bouche chez l’adulte, ou choc sur asystolie, ou palper le pouls 1 minute.", "reflexe": "MCE + DEA d’emblée, pas de bouche-à-bouche adulte. Choc = FV/TV. Asystolie = massage + adrénaline."},
    {"item": "330", "rang": "A", "piege": "Poursuivre l’héparine devant une TIH « parce que les plaquettes sont à 60 et il n’a pas saigné ».", "reflexe": "TIH = risque thrombotique. Stop toute héparine. Danaparoïde. Plaquettes 30–70 G/L typiques à J5–J10."},
    {"item": "330", "rang": "A", "piege": "HBPM ou AOD si DFG 22 ; AOD sur mécanique.", "reflexe": "HNF si IR sévère. AOD CI mécanique et RM."},
    {"item": "238", "rang": "A", "piege": "Rassurer un souffle diastolique ou néonatal « fonctionnel » ; prophylaxie EI pour tout souffle.", "reflexe": "Diastolique / néonatal / thrill = organique jusqu’à ETT. Prophylaxie = haut risque seulement."},
    {"item": "203", "rang": "A", "piege": "Traiter des sibilants du sujet âgé comme un asthme, ou diurétiques d’une tamponnade.", "reflexe": "Pseudoasthme cardiaque = OAP. Tamponnade = choc droit, remplissage + drainage, pas de diurétiques."},
    {"item": "231", "rang": "A", "piege": "BBG « bénin » ; ou ischémie devant des T− V1–V3 d’une HV droite / EP.", "reflexe": "BBG jamais bénin. T− droites : penser VD / EP. Dissociation VA de TV ≠ BAV complet."},
    {"item": "221", "rang": "A", "piege": "Compter une plaque carotidienne de 30 % dans le polyvasculaire.", "reflexe": "Sténose ≥ 50 % asx compte ; plaque non sténosante < 50 % ne compte pas."},
]

SEUILS = [
    {"group": "Lipides / prévention", "item": "223", "rang": "A", "label": "LDL secondaire / très haut risque", "value": "< 0,55 g/L et −50 %", "note": "Statine d’emblée. Inacceptable de l’ignorer (222)."},
    {"group": "Lipides / prévention", "item": "223", "rang": "A", "label": "Anti-PCSK9 (France)", "value": "LDL > 0,7 g/L sous ttt max", "note": "Après statine ± ézétimibe, en secondaire."},
    {"group": "Lipides / prévention", "item": "223", "rang": "A", "label": "Triglycérides", "value": "1,5–5 diète ; > 5 fibrate ; > 10 pancréatite", "note": "Si > 10 g/L avec chylomicrons : lipides < 30 g/j."},
    {"group": "Lipides / prévention", "item": "223", "rang": "A", "label": "Friedewald", "value": "LDL = CT − HDL − TG/5", "note": "Valable si TG < 3,5 g/L (unités g/L)."},
    {"group": "Pression artérielle", "item": "224", "rang": "A", "label": "Diagnostic cabinet", "value": "≥ 140/90 (222) ou > 140/90 (224)", "note": "AMT ≥ 135/85 ; MAPA 24 h ≥ 130/80. Deux formulations dans le collège."},
    {"group": "Pression artérielle", "item": "224", "rang": "A", "label": "Cible ESC 2024", "value": "PAS 120–129 / PAD 70–79", "note": "Adapter si > 85 ans, fragilité, HO. Atteindre en 3 mois."},
    {"group": "Pression artérielle", "item": "224", "rang": "A", "label": "Grade 3 / crise", "value": "PAS ≥ 180 et/ou PAD ≥ 110", "note": "Sans organe = crise, pas une urgence."},
    {"group": "Pression artérielle", "item": "224", "rang": "A", "label": "Urgence : baisse", "value": "−20–25 % en 2 h → 160/110 en 2–6 h", "note": "Dissection : PAS < 120 le plus vite possible."},
    {"group": "Pression artérielle", "item": "342", "rang": "A", "label": "Hypotension orthostatique", "value": "PAS −20 ou PAD −10 ou PAS < 90", "note": "Dans 1–3 min d’orthostatisme."},
    {"group": "Coronaires / DAPT", "item": "339", "rang": "A", "label": "PCI primaire", "value": "≤ 120 min", "note": "Sinon fibrinolyse + transfert. Bénéfice faible dès H12, nul dès H24."},
    {"group": "Coronaires / DAPT", "item": "339", "rang": "A", "label": "Coro ST−", "value": "< 2 h très haut risque ; < 24 h haut risque", "note": "GRACE > 140 = haut risque."},
    {"group": "Coronaires / DAPT", "item": "339", "rang": "A", "label": "DAPT", "value": "12 mois SCA ; 6 mois stent angor", "note": "Réduite 1–6 mois si haut risque hémorragique (SCA)."},
    {"group": "Coronaires / DAPT", "item": "339", "rang": "A", "label": "Oxygène SCA", "value": "SaO2 < 90 % ou PaO2 < 60", "note": "Hyperoxie délétère."},
    {"group": "Insuffisance cardiaque", "item": "234", "rang": "A", "label": "FEVG", "value": "< 40 HFrEF ; 41–49 HFmrEF ; > 50 HFpEF", "note": "HFmrEF traité comme HFrEF (preuve IIb)."},
    {"group": "Insuffisance cardiaque", "item": "234", "rang": "A", "label": "Nitrés OAP", "value": "SL si PAS > 100 ; IV si PAS > 110", "note": "Domicile vs hôpital. Pas de nitrés si choc."},
    {"group": "Insuffisance cardiaque", "item": "234", "rang": "A", "label": "CRT", "value": "FEVG ≤ 35 % et QRS ≥ 130 ms", "note": "Meilleure réponse si BBG et QRS ≥ 150 ms, non ischémique."},
    {"group": "Insuffisance cardiaque", "item": "234", "rang": "A", "label": "DAI 1aire", "value": "FEVG < 35 %, NYHA II–III, survie > 1 an", "note": "Pas le NYHA IV sauf greffe/assistance. ≥ 6 sem post-IDM ischémique."},
    {"group": "Insuffisance cardiaque", "item": "234", "rang": "A", "label": "BNP aigu (IC improbable)", "value": "BNP < 100 ; NT-proBNP < 300", "note": "Seuils d’âge NT-proBNP légèrement différents en 203 vs 234."},
    {"group": "FA / ACO", "item": "232", "rang": "A", "label": "CHA2DS2-VA", "value": "0–8 ; ACO si > 1", "note": "C1 H1 A2(≥75) D1 S2 V1 A(65–74). Pas de sexe. Inutile si mécanique/RM."},
    {"group": "FA / ACO", "item": "232", "rang": "A", "label": "Cardioversion", "value": "ACO 3 sem avant + 4 sem après", "note": "Sauf ETO sans thrombus ou FA < 24 h. CEE immédiat si choc."},
    {"group": "FA / ACO", "item": "232", "rang": "A", "label": "Cible FC", "value": "< 110 bpm à la marche", "note": "Holter. ICa brady interdits si IC systolique."},
    {"group": "Valves", "item": "233RA", "rang": "A", "label": "RA serré", "value": "Vmax > 4 m/s ; Gmoy > 40 ; S < 1 cm²", "note": "Opérer si sympto, ou asympto si FEVG < 55 % / Vmax > 5."},
    {"group": "Valves", "item": "233IM", "rang": "A", "label": "IM primaire sévère", "value": "SOR ≥ 40 mm² ; VR ≥ 60 mL", "note": "Secondaire : SOR 30 mm². Opérer si FEVG < 60 % ou DTS > 40 mm."},
    {"group": "Valves", "item": "153", "rang": "A", "label": "INR mécanique", "value": "2–3 (cible 2,5) ; 3–4,5 si mitrale/disque", "note": "AOD CI. Bioprotèse : pas d’ACO de principe au long cours."},
    {"group": "Valves", "item": "233RA", "rang": "A", "label": "TAVI", "value": "1re intention si > 75 ans + voie fémorale", "note": "Aussi inopérable / haut risque quel que soit l’âge."},
    {"group": "MTEV", "item": "226", "rang": "A", "label": "EP haut risque", "value": "PAS < 90 ou −40 mmHg > 15 min", "note": "Fibrinolyse + HNF. D-dimères inutiles si proba forte."},
    {"group": "MTEV", "item": "226", "rang": "A", "label": "D-dimères", "value": "> 500 ou âge × 10 si > 50 ans", "note": "Unités du texte : µg/L ou pg/L selon le chapitre — retenir le principe âge × 10."},
    {"group": "MTEV", "item": "226", "rang": "B", "label": "Durée ACO", "value": "Mini 3 mois ; 3 mois si facteur majeur transitoire", "note": "Sans facteur majeur : 6 mois. Cancer/SAPL/récidive : non limitée. Distale provoquée : 6 semaines."},
    {"group": "AOMI / AAA", "item": "225", "rang": "A", "label": "IPS", "value": "AOMI < 0,90 ; sévère < 0,70 ; > 1,40 médiacalcose", "note": "Index d’orteil < 0,70 si médiacalcose."},
    {"group": "AOMI / AAA", "item": "225", "rang": "A", "label": "AAA intervention", "value": "50–55 mm", "note": "221 B : 55 mm (50 mm femme) ou + 5 mm/an. Écho / 6 mois si > 45 mm."},
    {"group": "AOMI / AAA", "item": "225", "rang": "A", "label": "Ischémie critique", "value": "Cheville < 50 ou hallux < 30 mmHg", "note": "Douleurs > 15 j + ces pressions. Revasc autant que possible."},
    {"group": "Conduction / rythme", "item": "236", "rang": "A", "label": "Pauses / PR / QRS", "value": "Pause patho > 3 s ; PR > 200 ms ; QRS fin si < 120 ms", "note": "HV > 70 ms pathologique. PM si pauses > 6 s même asympto."},
    {"group": "Conduction / rythme", "item": "237", "rang": "A", "label": "WPW malin", "value": "PRE antérograde < 250 ms", "note": "Ablation formelle. FA + Kent : jamais de freinateur du NAV."},
    {"group": "Conduction / rythme", "item": "231", "rang": "A", "label": "ECG normal", "value": "FC 60–100 ; PR 120–200 ; QRS 70–110 ; QTc < 450", "note": "En pratique QTc 470–480 souvent retenu. FA = irrégulier QRS fins."},
    {"group": "Péricarde / tamponnade", "item": "235", "rang": "A", "label": "Épanchement", "value": "< 10 minime ; 10–20 modéré ; > 20 abondant (mm)", "note": "Pouls paradoxal : ΔPAS insp. 10 mmHg. QRS < 5 mm périph. = microvoltage."},
    {"group": "Péricarde / tamponnade", "item": "235", "rang": "A", "label": "Colchicine", "value": "0,5 mg × 2 / 3 mois", "note": "0,5 mg/j si < 70 kg, > 70 ans, DFG < 35. CI IRC sévère."},
    {"group": "ACR", "item": "331", "rang": "A", "label": "MCE", "value": "4–5 cm, ~ 100/min, relais / 2 min", "note": "Amiodarone 300 mg avant le 3e choc ; adrénaline 1 mg / 4 min."},
    {"group": "Mnémoniques", "item": "222", "rang": "A", "label": "BASIC", "value": "BB + AAP + Statine + IEC + Contrôle FDR", "note": "Post-IDM / secondaire coronaire. 4 classes médicamenteuses : chacune ~ −25 % mortalité totale."},
    {"group": "Mnémoniques", "item": "230", "rang": "A", "label": "PIED", "value": "Péricardite, Infarctus, EP, Dissection", "note": "4 urgences CV de la douleur thoracique. + rupture œsophage (rare)."},
    {"group": "Mnémoniques", "item": "331", "rang": "A", "label": "ACD", "value": "Airway, Circulation (MCE), Defibrillation", "note": "Pas de Breathing/bouche-à-bouche chez l’adulte."},
]


def main() -> None:
    data = json.loads(OUT.read_text(encoding="utf-8"))
    data["reflexes"] = REFLEXES
    data["pieges"] = PIEGES
    data["seuils"] = SEUILS
    OUT.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(
        f"comparatifs={len(data['comparatifs'])} reflexes={len(REFLEXES)} "
        f"pieges={len(PIEGES)} seuils={len(SEUILS)} -> {OUT}"
    )


if __name__ == "__main__":
    main()
